const cardsData = [
    {
        "id": "SP·01",
        "theme": "theme-supreme",
        "factionArcana": "NEUTRAL",
        "nameEn": "Game Moderator",
        "nameId": "Sang Narator",
        "ability": "Tuhan Desa Werewolf",
        "desc": "Tugas pemegang ini absolut, bukan lagi menjadi pemain. Anda dilarang memihak. Tugas Anda hanyalah mengatur malam dan siang, memandu langkah, serta <strong>Mencatut Nyawa</strong> pemain berdasarkan instruksi malam.",
        "footer": "Moderator — Supreme",
        "factionUp": "Khusus",
        "factionUpClass": "faction-supreme",
        "factionWm": "Khusus"
    },
    {
        "id": "VL·01",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Seer",
        "nameId": "Peramal",
        "ability": "Penerawang Identitas",
        "desc": "Setiap malam, peramal dapat menunjuk satu pemain. Moderator akan mengonfirmasi apakah pemain\n                    tersebut <strong>Serigala atau bukan</strong>. Pemain paling vital bagi pihak desa.",
        "footer": "Seer — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·02",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Guardian",
        "nameId": "Penjaga",
        "ability": "Pelindung Malam",
        "desc": "Setiap malam, memilih satu pemain untuk <strong>dilindungi</strong> dari serangan serigala. Penjaga\n                    tidak boleh melindungi dirinya atau pemain yang sama selama dua malam berturut-turut.",
        "footer": "Guardian — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·14",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Villager",
        "nameId": "Warga Desa",
        "ability": "Pemilik Suara Demokrasi",
        "desc": "Tidak memiliki kemampuan magis di malam hari. Kekuatan utama warga desa terletak pada kepekaan\n                    analitis dan <strong>hak suara (voting)</strong> di siang hari untuk menyingkirkan para serigala.",
        "footer": "Villager — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·15",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Villager",
        "nameId": "Warga Desa",
        "ability": "Pemilik Suara Demokrasi",
        "desc": "Tidak memiliki kemampuan magis di malam hari. Kekuatan utama warga desa terletak pada kepekaan\n                    analitis dan <strong>hak suara (voting)</strong> di siang hari untuk menyingkirkan para serigala.",
        "footer": "Villager — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·16",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Villager",
        "nameId": "Warga Desa",
        "ability": "Pemilik Suara Demokrasi",
        "desc": "Tidak memiliki kemampuan magis di malam hari. Kekuatan utama warga desa terletak pada kepekaan\n                    analitis dan <strong>hak suara (voting)</strong> di siang hari untuk menyingkirkan para serigala.",
        "footer": "Villager — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·17",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Villager",
        "nameId": "Warga Desa",
        "ability": "Pemilik Suara Demokrasi",
        "desc": "Tidak memiliki kemampuan magis di malam hari. Kekuatan utama warga desa terletak pada kepekaan\n                    analitis dan <strong>hak suara (voting)</strong> di siang hari untuk menyingkirkan para serigala.",
        "footer": "Villager — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "WW·01",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Werewolf",
        "nameId": "Serigala",
        "ability": "Membunuh di Malam Hari",
        "desc": "Setiap malam, serigala memilih satu pemain untuk <strong>dibunuh</strong>. Serigala saling\n                    mengetahui identitas koloninya. Menang jika jumlah serigala menyamai jumlah warga desa yang tersisa.",
        "footer": "Werewolf — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·02",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Werewolf",
        "nameId": "Serigala",
        "ability": "Membunuh di Malam Hari",
        "desc": "Setiap malam, serigala memilih satu pemain untuk <strong>dibunuh</strong>. Serigala saling\n                    mengetahui identitas koloninya. Menang jika jumlah serigala menyamai jumlah warga desa yang tersisa.",
        "footer": "Werewolf — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "VL·03",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Witch",
        "nameId": "Penyihir",
        "ability": "Pemilik Dua Ramuan",
        "desc": "Miliki 2 ramuan (1x pakai seumur hidup): Ramuan <strong>Kehidupan</strong> untuk menyelamatkan\n                    korban malam itu, dan Ramuan <strong>Kematian</strong> untuk membunuh siapapun secara instan.",
        "footer": "Witch — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·04",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Hunter",
        "nameId": "Pemburu",
        "ability": "Tembakan Terakhir",
        "desc": "Jika pemburu terbunuh karena eksekusi siang hari, ia dapat melancarkan tembakan terakhir untuk\n                    membunuh <strong>satu pemain lain</strong> sebelum ia benar-benar mati sebagai balas dendam.",
        "footer": "Hunter — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·05",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "King",
        "nameId": "Raja",
        "ability": "Hak Veto Eksekusi",
        "desc": "Raja adalah bangsawan desa. Memiliki kuasa untuk membatalkan eksekusi siang hari secara mutlak.\n                    Kemampuan istimewa ini hanya dapat digunakan <strong>satu kali</strong> sepanjang permainan.",
        "footer": "King — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·06",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Drunker",
        "nameId": "Pemabuk",
        "ability": "Pesta Keras Malam Ini",
        "desc": "Setiap malam mengajak satu pemain untuk minum. Pemain yang diajak mabuk <strong>kehilangan\n                        kemampuannya</strong> malam itu. Serigala atau Peramal yang diajak akan gagal beraksi tanpa\n                    sadar.",
        "footer": "Drunker — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·07",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Little Girl",
        "nameId": "Gadis Kecil",
        "ability": "Pengintip Malam",
        "desc": "Bisa membuka mata perlahan saat Serigala beraksi untuk mengetahui identitas mereka. <strong>Risiko\n                        Tinggi:</strong> Jika Serigala menyadari ia mengintip, gadis kecil langsung dibantai di tempat!",
        "footer": "Little Girl — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·09",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Sheriff",
        "nameId": "Polisi",
        "ability": "Pemegang Otoritas Tinggi",
        "desc": "Polisi sering kali ditunjuk oleh warga secara terbuka. Suaranya bernilai <strong>dua poin</strong>\n                    pada saat voting eksekusi siang hari. Posisi terbuka ini menjadikannya target yang menggiurkan.",
        "footer": "Sheriff — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "WW·03",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Alpha Wolf",
        "nameId": "Alpha Serigala",
        "ability": "Pemimpin Kawanan",
        "desc": "Pemimpin utama. Memiliki hak veto saat memilih korban. Satu kali dalam permainan, ia dapat\n                    <strong>menginfeksi</strong> satu pemain warga menjadi serigala alih-alih membunuhnya.",
        "footer": "Alpha Wolf — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "NT·01",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Jester",
        "nameId": "Badut",
        "ability": "Tawa Terakhir",
        "desc": "Tujuan utamanya hanya satu, yaitu memprovokasi agar <strong>dieksekusi</strong> warga di siang hari.\n                    Jika Badut berhasil membuat dirinya digantung, maka ia memenangkan permainan seorang diri.",
        "footer": "Jester — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·03",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Cupid",
        "nameId": "Cupid",
        "ability": "Penyatu Dua Jiwa",
        "desc": "Pada malam pertama, menunjuk dua pemain untuk menjadi sepasang <strong>kekasih abadi</strong>. Jika\n                    salah satu mati, yang lain otomatis mati patah hati. Pasangan ini harus bertahan hidup bersama.",
        "footer": "Cupid — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "VL·08",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Harlot",
        "nameId": "Pelacur",
        "ability": "Tamu Misterius",
        "desc": "Tidur di rumah pemain lain tiap malam. Jika rumah yang dikunjungi diserang Serigala, ia ikut mati.\n                    Jika ia mengunjungi Serigala, ia dibunuh. Selamat jika diam di rumah (namun berisiko).",
        "footer": "Harlot — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·10",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Mayor",
        "nameId": "Kepala Desa",
        "ability": "Hak veto tunggal",
        "desc": "Tokoh yang sangat disegani warga. Suara votingnya dihitung normal, namun ia memiliki hak mutlak\n                    untuk membatalkan hasil akhir eksekusi desa <strong>satu kali</strong> jika dirasa ada konspirasi di\n                    dalamnya.",
        "footer": "Mayor — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·11",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Detective",
        "nameId": "Detektif",
        "ability": "Investigasi Identitas",
        "desc": "Setiap malam, detektif menunjuk <strong>dua pemain</strong>. Moderator akan memberi isyarat apakah\n                    kedua pemain itu berada di tim yang sama atau berbeda (tanpa menyebutkan perannya apa).",
        "footer": "Detective — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·12",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Medium",
        "nameId": "Medium",
        "ability": "Penghubung Arwah",
        "desc": "Mampu berkomunikasi dengan para korban yang telah tewas. Setiap malam dapat menanyakan satu\n                    pertanyaan <strong>\"Ya atau Tidak\"</strong> pada arwah. Sangat berguna mencari petunjuk tersisa.",
        "footer": "Medium — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·13",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Wizard",
        "nameId": "Penyihir Penukar",
        "ability": "Menukar Peran Dua Pemain",
        "desc": "Di fase malam, ia dapat menunjuk dua pemain kepada moderator. Sang moderator akan menukar secara\n                    diam-diam <strong>kartu peran kedua pemain</strong> tanpa disadari hingga terungkap di kemudian\n                    hari.",
        "footer": "Wizard — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·18",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Bodyguard",
        "nameId": "Prajurit",
        "ability": "Perisai Nyawa",
        "desc": "Melindungi satu pemain setiap malam. Perbedaannya dengan Penjaga, jika target yang dilindungi diserang, <strong>Prajuritlah yang akan terbunuh</strong> menggantikan target tersebut.",
        "footer": "Bodyguard — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·19",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Priest",
        "nameId": "Pendeta",
        "ability": "Pemilih Air Suci",
        "desc": "Memiliki <strong>botol air suci</strong> (1x pakai). Dilempar ke 1 pemain malam hari. Jika pemain itu Serigala, Serigala langsung musnah. Tapi jika disiram ke manusia biasa, Pendeta yang mati.",
        "footer": "Priest — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·20",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Veteran",
        "nameId": "Veteran Tua",
        "ability": "Kulit Keras Penuh Luka",
        "desc": "Pensiunan militer yang luar biasa tangguh. Jika ia didatangi serigala di malam hari, ia <strong>tidak langsung mati</strong>. Ia akan bertahan membisu dan baru gugur keesokan siangnya akibat luka-luka gawat.",
        "footer": "Veteran — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·21",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Apprentice Seer",
        "nameId": "Murid Peramal",
        "ability": "Pewaris Mata Batin",
        "desc": "Mulai layaknya warga biasa. Tapi jika <strong>Peramal asli terbunuh</strong>, maka malam itu juga potensinya bangkit, dan ia mewarisi penuh tugas Peramal untuk menerawang satu pemain tiap malamnya.",
        "footer": "Apprentice Seer — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·22",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Aura Seer",
        "nameId": "Penerawang Aura",
        "ability": "Mendeteksi Kekuatan",
        "desc": "Tiap malam dapat menunjuk 1 pemain. Moderator akan memberitahu apakah pemain tersebut <strong>punya kemampuan spesial</strong> (termasuk serigala/peran unik) atau hanya warga/makhluk pasif tanpa kemampuan.",
        "footer": "Aura Seer — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·23",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Beholder",
        "nameId": "Sang Pengawas",
        "ability": "Mata Tersembunyi",
        "desc": "Hanya terbangun sekali di malam pertama. Ia akan ditunjukkan <strong>siapa yang memegang peran Peramal (Seer)</strong>. Tugasnya melindungi Peramal dalam argumen siang hari tanpa membongkar pengetahuannya.",
        "footer": "Beholder — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·24",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Diseased",
        "nameId": "Warga Berpenyakit",
        "ability": "Darah Beracun",
        "desc": "Warga dengan penyakit kutukan. Jika kawanan serigala memangsa dirinya, maka kawanan serigala tersebut <strong>jatuh sakit kelaparan</strong> dan tidak boleh memangsa siapapun pada malam hari berikutnya.",
        "footer": "Diseased — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·25",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Ghost",
        "nameId": "Hantu Gentayangan",
        "ability": "Pesan Dari Kubur",
        "desc": "Jika ia tewas terbunuh di <strong>Malam Pertama</strong>, ia mengubah statusnya menjadi arwah informan. Setiap bangun esok harinya, dapat menyumbangkan <strong>1 huruf</strong> gaib yang ditulis Moderator ke warga.",
        "footer": "Ghost — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·26",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Village Idiot",
        "nameId": "Orang Dungu",
        "ability": "Kebal Hukuman Mati",
        "desc": "Pemain yang memicu jengkel warga. Jika ia diputuskan <strong>dieksekusi mati</strong> pada musyawarah siang hari, ia membuka identitasnya dan **tidak jadi dibunuh**! Tapi hak votingnya hangus selamanya.",
        "footer": "Idiot — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·27",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Insomniac",
        "nameId": "Insomnia",
        "ability": "Bangun Semalaman",
        "desc": "Warga yang selalu terjaga. Di pagi hari ia berhak bertanya sembunyi-sembunyi pada Moderator: <strong>\"Apakah peran/tubuhku ditukar semalam?\"</strong>. Sangat berguna menangkal kekuatan tukar-kopi faksi gelap.",
        "footer": "Insomniac — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·28",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Martyr",
        "nameId": "Sang Martir",
        "ability": "Tebusan Dosa Darah",
        "desc": "Memiliki hak krusial (hanya berlaku 1x) untuk <strong>mengambil alih kematian mangsa Serigala</strong> di malam hari. Target serigala akan diampuni, dan sang Martir mengambil posisi mengorbankan nyawanya.",
        "footer": "Martyr — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·29",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Mason",
        "nameId": "Tukang Batu",
        "ability": "Persaudaraan Gelap",
        "desc": "Warga bagian dari sindikat. Di fase formasi awal malam pertama, **semua Mason saling terbangun**. Mereka merupakan satu-satunya duo/trio warga yang <strong>pasti jujur</strong> tentang satu sama lain.",
        "footer": "Mason — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·30",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Mason",
        "nameId": "Tukang Batu",
        "ability": "Persaudaraan Gelap",
        "desc": "Warga bagian dari sindikat. Di fase formasi awal malam pertama, **semua Mason saling terbangun**. Mereka merupakan satu-satunya duo/trio warga yang <strong>pasti jujur</strong> tentang satu sama lain.",
        "footer": "Mason — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·31",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Old Hag",
        "nameId": "Nenek Sihir Tua",
        "ability": "Aura Pengusir",
        "desc": "Setiap malam ia menunjuk 1 pemain. Keesokan harinya, pemain yang ditunjuk <strong>dilarang mengikuti voting/berkomentar</strong> dalam diskusi siang! Sangat berguna membatasi bicara suspek perusuh.",
        "footer": "Old Hag — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·32",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Old Man",
        "nameId": "Kakek Renta",
        "ability": "Waktu yang Terbatas",
        "desc": "Penduduk tertua di desa. Ia <strong>akan mati otomatis di fajar hari ke-X</strong> (hari ke-X ditentukan saat permainan dimulai berdasarkan jumlah pemain). Sang Kakek berpacu dengan waktu sebelum ia mati.",
        "footer": "Old Man — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·33",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Paranormal Investigator",
        "nameId": "Penyidik Gaib",
        "ability": "Inspeksi Suara Serigala",
        "desc": "Mengecek 1 sasaran (dan orang di sebelahnya). Mengetahui *\"Adakah Serigala di area tersebut?\"*. Namun <strong>bila ada Serigala</strong> yang tertangkap sinyal radarnya, maka P.I juga berubah jadi serigala!",
        "footer": "Detektif Mistik — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·34",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Pacifist",
        "nameId": "Cinta Damai",
        "ability": "Pemaksa Gencatan Senjata",
        "desc": "Warga ini wajib melakukan \"Abstain / Nol Voting\". Sekali per permainan, ia bisa mendeklarasikan pengampunan yang membatalkan hukuman eksekusi siang hari, menghentikan penumpahan darah hari itu!",
        "footer": "Pacifist — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·35",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Prince",
        "nameId": "Pangeran Elit",
        "ability": "Titah Darah Mahkota",
        "desc": "Bangsawan rahasia yang turun gunung. Jika voting warga di balai desa sepakat menggantungnya, sang Prince akan mengungkap identitas dan ia <strong>bebas dari jerat eksekusi</strong> (hanya berlaku kebal 1x seumur hidup)!",
        "footer": "Prince — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·36",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Spellcaster",
        "nameId": "Perapal Mantra",
        "ability": "Kutukan Bisu Magis",
        "desc": "Tiap malam memilih 1 pemain untuk dikutuk lidahnya. Saat esok siangnya, pemain tersebut <strong>100% Bisul/Bisu</strong>: tidak boleh bicara, mengetik (chat), apalagi berdebat (namun ia tetap bisa ikut menunjuk untuk divote).",
        "footer": "Spellcaster — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·37",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Tough Guy",
        "nameId": "Jagoan Kampung",
        "ability": "Urat Kawat Tulang Besi",
        "desc": "Warga paling kekar. Jika diterkam Serigala di malam hari, ia <strong>membutuhkan waktu lama untuk mati</strong>. Ia akan terus bertahan di persidangan esok paginya. Saat malam <em>kedua</em> setelah digigit, ia mati otomatis.",
        "footer": "Tough Guy — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·38",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Troublemaker",
        "nameId": "Pembuat Onar",
        "ability": "Pengacau Malam Buta",
        "desc": "Setiap malam diam-diam ia dapat memilih 2 pemain (selain dirinya). Ke-dua pemain tersebut (baik peran dan fisik mereka) <strong>Tukar Nasib/Posisi</strong> dan peran mereka tertukar tanpa mereka menyadarinya!",
        "footer": "Troublemaker — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "VL·39",
        "theme": "theme-good",
        "factionArcana": "ALLIANCE",
        "nameEn": "Fortune Teller",
        "nameId": "Pembaca Nasib",
        "ability": "Bedah Identitas Mati",
        "desc": "Tiap malam memilih 1 pemain. Namun, ia bertugas untuk membuka dan mengetahui <strong>identitas kartu pemain yang baru saja dibunuh/dieksekusi</strong>, memastikan apakah sisa ancaman desa sudah benar-benar lenyap!",
        "footer": "Fortune Teller — Tim Desa",
        "factionUp": "Baik",
        "factionUpClass": "faction-good",
        "factionWm": "Baik"
    },
    {
        "id": "WW·04",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Lycan",
        "nameId": "Likat",
        "ability": "Penyamaran Sempurna",
        "desc": "Anggota tim jahat dengan aura kemanusiaan yang kuat. Jika diperiksa oleh sang Peramal, identitasnya\n                    akan muncul sebagai <strong>Orang Baik/Warga</strong>! Penyusup paling sulit diidentifikasi.",
        "footer": "Lycan — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·05",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Lone Wolf",
        "nameId": "Serigala Penyendiri",
        "ability": "Berubah Saat Ditemukan Werewolf",
        "desc": "Awalnya berstatus warga biasa. Namun ketika Serigala memeriksa dan \"menemukan\" Lone Wolf di malam\n                    hari, ia langsung berubah menjadi <strong>Serigala penuh</strong> dan bergabung dengan kawanan.",
        "footer": "Lone Wolf — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·06",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Sorcerer",
        "nameId": "Penyihir Jahat",
        "ability": "Mencari Peramal di Fase Malam",
        "desc": "Berada di pihak Serigala. Setiap malam, ia bisa menerawang untuk mencari siapa yang berperan sebagai\n                    <strong>Peramal</strong> demi membocorkan informasi dan memburu tokoh paling berbahaya bagi kawanan.",
        "footer": "Sorcerer — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·07",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Minion",
        "nameId": "Kaki Tangan",
        "ability": "Sekte Pengabdi Sang Alpha",
        "desc": "Sekutu manusia para serigala. Ia diberi tahu identitas kawanan Serigala, namun serigala tak tahu siapa dia. Karena aslinya manusia, jika diterawang ia akan tampil sebagai <strong>Orang Baik</strong>!",
        "footer": "Minion — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·08",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Wolf Cub",
        "nameId": "Anak Serigala",
        "ability": "Pemicu Balas Dendam",
        "desc": "Bagian dari Serigala, imut tapi berbahaya. Jika ia sampai terbunuh (entah dieksekusi siang atau ditembak pemburu), kawanannya murka dan akan memangsa <strong>Dua Orang Sekaligus</strong> di malam esok.",
        "footer": "Wolf Cub — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·09",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Big Bad Wolf",
        "nameId": "Serigala Raksasa",
        "ability": "Haus Darah Ganda",
        "desc": "Setelah kawanan serigala biasa selesai memangsa satu korban, moderator akan membangunkannya kembali <strong>sendirian</strong> agar ia memangsa ekstra <strong>satu korban lagi</strong> di malam yang sama!",
        "footer": "Big Bad Wolf — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·10",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "White Wolf",
        "nameId": "Serigala Putih",
        "ability": "Pengkhianat Kawanan",
        "desc": "Malam hari ia terbangun bersama serigala lain. Namun setiap <strong>2 malam sekali</strong>, ia terbangun lagi sendirian untuk memangsa <strong>sesama werewolf lainnya</strong>. Ia menang hanya jika hidup sendirian!",
        "footer": "White Wolf — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·11",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Dream Wolf",
        "nameId": "Serigala Tidur",
        "ability": "Monster Pemalas",
        "desc": "Bagian dari faksi jahat, tapi ia tak mau direpotkan. Saat serigala lain dipanggil untuk berunding/membunuh malam hari, <strong>ia tidak ikut bangun</strong>. Ia tak tahu siapa sesama serigalanya!",
        "footer": "Dream Wolf — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·12",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Dire Wolf",
        "nameId": "Serigala Buas",
        "ability": "Sumpah Kesetiaan",
        "desc": "Malam pertama ia menunjuk 1 pemain (kawan/lawan). Pasangannya itu disebut \"Blood Brother\". Jika sang Blood Brother suatu saat mati terbunuh, ia mengamuk dan akan menargetkan kemarahan mengerikan!",
        "footer": "Dire Wolf — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·13",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Black Wolf",
        "nameId": "Serigala Hitam",
        "ability": "Kegelapan Mutlak",
        "desc": "Pemimpin bayangan kawanan. Selama ia hidup menangkap aura, <strong>tidak ada serigala lain yang bisa terdeteksi</strong> oleh kemampuan \"P.I\" atau \"Aura Seer\". Ia melindungi rekam jejak timnya.",
        "footer": "Black Wolf — Tim Jahat",
        "factionUp": "Jahat",
        "factionUpClass": "faction-evil",
        "factionWm": "Jahat"
    },
    {
        "id": "WW·14",
        "theme": "theme-evil",
        "factionArcana": "SHADOWS",
        "nameEn": "Wolf Man",
        "nameId": "Manusia Serigala",
        "ability": "Genetika Terkutuk",
        "desc": "Unik! Fisiknya mirip monster sehingga wujud kartunya merah. <strong>Ia beraliansi sepenuh hati dengan Warga Desa</strong>. Namun, jika Seer menerawangnya ia selalu terlihat sebagai Serigala tulen!",
        "footer": "Wolf Man — Tim Desa (?)",
        "factionUp": "Baik (Unik!)",
        "factionUpClass": "faction-evil",
        "factionWm": "Baik (Unik!)"
    },
    {
        "id": "NT·02",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Tanner",
        "nameId": "Penyamak",
        "ability": "Mencari Kematian",
        "desc": "Pemain depresif yang memenangkan permainan <strong>HANYA</strong> jika dirinya dieksekusi mati oleh\n                    voting warga. Jika mati terbunuh Serigala, ia kalah. Bertingkahlah sangat mencurigakan!",
        "footer": "Tanner — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·04",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Doppelganger",
        "nameId": "Peniru",
        "ability": "Mengambil Alih Peran Pemain Lain",
        "desc": "Hanya bangun di malam pertama untuk memilih target. Jika target tersebut mati, sang Peniru akan\n                    <strong>mewarisi peran</strong> targetnya secara rahasia dan bermain dengan tujuan tim barunya.",
        "footer": "Doppelganger — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·05",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Serial Killer",
        "nameId": "Pembunuh Berantai",
        "ability": "Ancaman Gelap Independen",
        "desc": "Misi individunya satu: Menang dengan cara menjadi Survivor terakhir! Setiap malam ia kebal terkaman serigala, dan dapat <strong>menusuk mati 1 pemain</strong> mana pun (baik warga/serigala) secara ganas!",
        "footer": "Serial Killer — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·06",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Cult Leader",
        "nameId": "Pemimpin Sekte",
        "ability": "Misi Perekrutan Massal",
        "desc": "Setiap kelam ia merekrut 1 pemain rahasia masuk faksi sektenya. Anggota tahu mereka bergabung, tapi tidak tau siapa saja anggotanya. Menang mutlak jika dan hanya jika <strong>seluruh pemain sisa adalah anggota kultus!</strong>",
        "footer": "Cult Leader — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·07",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Cursed",
        "nameId": "Darah Terkutuk",
        "ability": "Evolusi Monster Tidur",
        "desc": "Dimana ia diperiksa oleh si peramal ia adalah <strong>Warga Biasa</strong>. Namun pudar saat serigala menyerangnya; si terkutuk tidak mati melainkan lolos maut untuk <strong>Berubah Menjadi Serigala Tambahan!</strong>",
        "footer": "Cursed — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·08",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Vampire",
        "nameId": "Vampir",
        "ability": "Ancaman Malam ke-2",
        "desc": "Faksi jahat tersendiri (memusuhi Desa dan Serigala). Bangun tiap malam lalu menunjuk 1 orang, besoknya orang itu akan <strong>menunda ajalnya 1 hari</strong> sebelum tewas divakum darahnya (kecuali dibantu tabib).",
        "footer": "Vampire — Tim Vampir",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·09",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "The Count",
        "nameId": "Sang Tuan Vampir",
        "ability": "Pewabahan Eksklusif",
        "desc": "Pemimpin ras penghisap darah. Tiap malam menunjuk 1 calon. Namun jika The Count bertahan hingga akhir, calon mangsanya itu tidak terbunuh melainkan <strong>bermutasi menjadi kawan se-vaksinya</strong>!",
        "footer": "The Count — Tim Vampir",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·10",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Chupacabra",
        "nameId": "Penghisap Darah",
        "ability": "Mengkopi Kekuatan Hewan",
        "desc": "Makhluk mitos malam. Ia membunuh 1 orang tiap malam. Jika yang dibunuh (tanpa ia tahu) kebetulan adalah seekor <strong>Werewolf</strong>, ia tidak membunuhnya namun justru menyalin kekuatan Serigala tersebut.",
        "footer": "Chupacabra — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·11",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Bogeyman",
        "nameId": "Sang Momok (Genderuwo)",
        "ability": "Sembunyi Dalam Gelap",
        "desc": "Target utamanya adalah kekacauan. Ia hanya bisa menang jika para <strong>Serigala/Warga tersesat secara ajaib mengeksekusi dia di Malam Hari</strong> (akibat efek tukar role). Sangat rumit menebak alurnya.",
        "footer": "Bogeyman — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·12",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Hoodlum",
        "nameId": "Sang Preman",
        "ability": "Kontrak Pembunuhan Terselubung",
        "desc": "Pada malam pertama ia menunjuk <strong>2 karakter acak</strong>. Misinya tunggal: Hoodlum baru bisa mengklaim kemenangannya jika di hari penentuan kedua karakter tersangkanya mati, dan ia sendiri tidak dibunuh.",
        "footer": "Hoodlum — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·13",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Wild Child",
        "nameId": "Anak Rimba Liar",
        "ability": "Panutan Menentukan Faksi",
        "desc": "Malam pertama memilih 1 <strong>Panutan (Role Model)</strong>. Selama Panutan hidup, ia adalah Warga tulen. Namun jika Sang Panutan mati tak sempat selamat, Anak Liar otomatis <strong>berubah jadi Serigala</strong> buas.",
        "footer": "Wild Child — Tim Variabel",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·14",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Sasquatch",
        "nameId": "Bigfoot (Sasquatch)",
        "ability": "Adaptasi Keadaan Bertahan",
        "desc": "Dianggap makhluk pasif hari ke-1 (hidup menyendiri). Jika permainan berlangsung lebih dari sejumlah fajar tanpa ia tersingkir, <strong>ia mendadak memiliki faksi penentu</strong> antara Serigala atau Desa yang menguasai jalannya game!",
        "footer": "Sasquatch — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·15",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Leprechaun",
        "nameId": "Peri Penipu",
        "ability": "Tipu Balik Kematian",
        "desc": "Penganut aliran jahil yang kebal deteksi. Menyelinap malam usai Serigala menyerang. Ia bisa menunjuk orang lain secara acak, dan keajaiban jahatnya memindah <strong>bekas terkaman kematian Serigala</strong> ke orang yang ia tunjuk!",
        "footer": "Leprechaun — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·16",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Bloody Mary",
        "nameId": "Hantu Kaca",
        "ability": "Hukuman Terhadap Ke-Sok-Tahuan",
        "desc": "Roh penasaran. Jika seorang pemain dengan ceroboh dan jelas menyebutkan nama peran \"Bloody Mary\" atau mencurigainya sepanjang hari dengan lantang, malam harinya **pemain yang memanggilnya tersebut tewas membusuk**.",
        "footer": "Bloody Mary — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·17",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "The Thing",
        "nameId": "Makhluk Rawa Misterius",
        "ability": "Menyentuh Orang Sebelah",
        "desc": "(Perlu dimainkan fisik). Tiap malam ia mendapat jatah <strong>mencolek/menyenggol pundak 1 orang yang duduk tepat di kirinya/kanannya</strong> secara fisik diam-diam. Menciptakan kecurigaan paranioia ke pagi hari!",
        "footer": "The Thing — Tim Netral",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    },
    {
        "id": "NT·18",
        "theme": "theme-neutral",
        "factionArcana": "NEUTRAL",
        "nameEn": "Nostradamus",
        "nameId": "Peramal Kuno Akhir Zaman",
        "ability": "Ramalan Mutlak Pemenang",
        "desc": "Malam pertama, ia menulis tebakan siapakah Faksi yang akan menang! (Desa atau Serigala). Segel dan jangan diubah. Jika tebakkannya tepat di akhir peperangan, Nostradamus merenggut kursi kemenangan bersama mereka.",
        "footer": "Nostradamus — Tim Ketiga",
        "factionUp": "Netral",
        "factionUpClass": "faction-neutral",
        "factionWm": "Netral"
    }
];
