const carntickDeckData = [
  {
    id: 'alpha-wolf',
    isBack: false,
    roleClass: 'role-alpha-wolf',
    faction: 'SHADOWS',
    serial: 'TKT·AW·01',
    titleEn: 'ALPHA WOLF',
    titleId: 'Sang Pemimpin Kawanan',
    quote: '"Akulah yang memimpin orkestra malam ini. Seluruh arena ini adalah <span>kandangku.</span>"',
    abilityTitle: 'HOWL OF COMMAND (MALAM)',
    abilityDesc: 'Pemimpin Serigala. Tiap malam kamu bisa <b>Merekrut</b> 1 Warga menjadi Serigala Biasa, ATAU memilih mangsa bersama kawananmu.'
  },
  {
    id: 'cupid',
    isBack: false,
    roleClass: 'role-cupid',
    faction: 'ALLIANCE',
    serial: 'TKT·CU·02',
    titleEn: 'CUPID',
    titleId: 'Sang Mak Comblang',
    quote: '"Ah, cinta di karnaval... Pastikan anak panah ini <span>mengikat kalian berdua</span> sampai maut memisahkan."',
    abilityTitle: 'BUSUR ASMARA (MALAM 1)',
    abilityDesc: 'Pada malam pertama, tunjuk <b>2 pemain</b>. Mereka jatuh cinta — jika satu mati, yang lain ikut mati. Mereka menang bersama!'
  },
  {
    id: 'witch',
    isBack: false,
    roleClass: 'role-witch',
    faction: 'ALLIANCE',
    serial: 'TKT·WT·03',
    titleEn: 'WITCH',
    titleId: 'Sang Penyihir',
    quote: '"Dua ramuan. Dua takdir. Ingat: sekali pakai, habis. Pikirkan baik-baik <span>sebelum menuangnya.</span>"',
    abilityTitle: 'RAMUAN GANDA (MALAM)',
    abilityDesc: 'Kamu punya 2 ramuan, masing-masing 1x: <b>Ramuan Hidup</b> (selamatkan mangsa malam ini) & <b>Ramuan Mati</b> (bunuh siapapun).'
  },
  {
    id: 'wizard',
    isBack: false,
    roleClass: 'role-wizard',
    faction: 'ALLIANCE',
    serial: 'TKT·WZ·04',
    titleEn: 'WIZARD',
    titleId: 'Sang Penyihir Agung',
    quote: '"Ilmu gaib bukan untukmu, Serigala. Kekuatanmu... <span>sudah ada di tanganku.</span>"',
    abilityTitle: 'MANTRA REFLEKSI (MALAM)',
    abilityDesc: 'Sekali per permainan: <b>Pantulkan</b> serangan serigala malam ini kembali ke penyerang. Kamu bisa memilih satu pemain untuk <b>Kebal</b> 1 malam.'
  },
  {
    id: 'veteran',
    isBack: false,
    roleClass: 'role-veteran',
    faction: 'ALLIANCE',
    serial: 'TKT·VT·05',
    titleEn: 'VETERAN',
    titleId: 'Sang Prajurit Tua',
    quote: '"Aku sudah melihat terlalu banyak karnaval berdarah. Malam ini... <span>aku siap tempur.</span>"',
    abilityTitle: 'SIAGA TEMPUR (MALAM)',
    abilityDesc: 'Sekali per permainan: Aktifkan <b>Mode Waspada</b>. Siapapun yang menemuimu malam itu — termasuk kawan — akan <b>mati seketika!</b>'
  },
  {
    id: 'moderator',
    isBack: false,
    roleClass: 'role-moderator',
    faction: 'THE CARNIVAL',
    serial: 'TKT·MD·00',
    titleEn: 'MODERATOR',
    titleId: 'Sang Dalang',
    quote: '"Selamat datang, tuan-tuan dan nona-nona... di mana <span>malam ini</span>, salah satu dari kalian tidak akan pulang."',
    abilityTitle: 'PENGUASA PANGGUNG',
    abilityDesc: 'Kamu adalah <b>Narator Mutlak</b>. Pimpin jalannya malam dan siang. Aturanmu adalah hukum. Tidak ada yang bisa mematikanmu.'
  },
  {
    id: 'seer',
    isBack: false,
    roleClass: 'role-seer',
    faction: 'ALLIANCE',
    serial: 'TKT·SR·01',
    titleEn: 'SEER',
    titleId: 'Sang Peramal',
    quote: '"Tataplah bola kristalku, sayang... Ah, aku bisa melihat <span>bulu dan darah</span> menyelimuti masa depanmu."',
    abilityTitle: 'MATA BATIN (MALAM)',
    abilityDesc: 'Buka matamu tiap malam. Tunjuk 1 pemain, dan Sang Narator akan membocorkan apakah ia <b>Serigala</b> atau bukan.'
  },
  {
    id: 'hunter',
    isBack: false,
    roleClass: 'role-hunter',
    faction: 'ALLIANCE',
    serial: 'TKT·HN·99',
    titleEn: 'HUNTER',
    titleId: 'Sang Pemburu',
    quote: '"Ini bukan permainan lempar gelang. Hadiah utama malam ini adalah <span>kepalamu yang berlubang.</span>"',
    abilityTitle: 'TEMBAKAN TERAKHIR',
    abilityDesc: 'Jika kamu mati dibunuh serigala atau dieksekusi warga, kamu berhak <b>menarik pelatuk</b> dan menembak mati 1 pemain lain secara instan!'
  },
  {
    id: 'werewolf',
    isBack: false,
    roleClass: 'role-werewolf',
    faction: 'SHADOWS',
    serial: 'TKT·WW·06',
    titleEn: 'WEREWOLF',
    titleId: 'Sang Serigala',
    quote: '"Buka tirainya lebar-lebar. Biarkan mereka melihat <span>monster sesungguhnya</span> sebelum fajar tiba."',
    abilityTitle: 'NALURI PEMANGSA (MALAM)',
    abilityDesc: 'Bangun bersama kawananmu saat malam. Diskusikan dan pilih <b>1 mangsa</b> untuk dicabik-cabik dari arena permainan.'
  },
  {
    id: 'jester',
    isBack: false,
    roleClass: 'role-jester',
    faction: 'CHAOS',
    serial: 'TKT·JS·00',
    titleEn: 'JESTER',
    titleId: 'Sang Badut',
    quote: '"Silakan hukum gantung badut ini! Kematianku adalah <span>puncak komedi</span> di karnaval gila kalian!"',
    abilityTitle: 'MANIPULASI SEMPURNA',
    abilityDesc: 'Faksi Independen. Kamu <b>MENANG MUTLAK</b> sendirian jika berhasil memprovokasi warga untuk memvoting eksekusimu di siang hari.'
  },
  {
    id: 'guardian',
    isBack: false,
    roleClass: 'role-guardian',
    faction: 'ALLIANCE',
    serial: 'TKT·GD·77',
    titleEn: 'GUARDIAN',
    titleId: 'Sang Penjaga',
    quote: '"Tanpa stempel dariku, tidak ada yang boleh lewat. Bahkan <span>kematian sekalipun</span> harus antre malam ini."',
    abilityTitle: 'AEGIS SUCI (MALAM)',
    abilityDesc: 'Tunjuk 1 pemain tiap malam. Ia akan mendapat <b>Perlindungan Mutlak</b> dari serangan mematikan serigala pada malam tersebut.'
  },
  {
    id: 'bodyguard',
    isBack: false,
    roleClass: 'role-bodyguard',
    faction: 'ALLIANCE',
    serial: 'TKT·BG·08',
    titleEn: 'BODYGUARD',
    titleId: 'Sang Pengawal',
    quote: '\"Di karnaval ini aku adalah perisai hidup. Tubuhku yang akan menanggung <span>peluru serigala itu.</span>\"',
    abilityTitle: 'PELINDUNG SEJATI (MALAM)',
    abilityDesc: 'Pilih 1 pemain untuk dijaga. Jika ia diserang serigala, <b>kamu yang mati</b> menggantikannya. Tidak bisa melindungi diri sendiri.'
  },
  {
    id: 'priest',
    isBack: false,
    roleClass: 'role-priest',
    faction: 'ALLIANCE',
    serial: 'TKT·PR·09',
    titleEn: 'PRIEST',
    titleId: 'Sang Pendeta',
    quote: '\"Cahaya suci ini bukan untuk pertunjukan. Ia hadir untuk membakar <span>kegelapan yang bersembunyi</span> di antara kalian.\"',
    abilityTitle: 'BERKAT ILAHI (SIANG)',
    abilityDesc: 'Sekali per permainan: <b>Berkati</b> 1 pemain. Ia tidak dapat dieksekusi oleh vote warga hari itu. Atau <b>Usir</b> setan dari 1 pemain (tidak berlaku pada Serigala).'
  },
  {
    id: 'mayor',
    isBack: false,
    roleClass: 'role-mayor',
    faction: 'ALLIANCE',
    serial: 'TKT·MR·10',
    titleEn: 'MAYOR',
    titleId: 'Sang Walikota',
    quote: '\"Kupegang mikrofon dan mandat rakyat. Vote-ku setara <span>dua suara</span> — terima kasih sudah memilih!\"',
    abilityTitle: 'SUARA GANDA (SIANG)',
    abilityDesc: 'Vote-mu diberi bobot <b>2 suara</b>. Jika kamu mengungkap identitasmu secara publik, vote-mu menjadi <b>3 suara</b> namun kamu jadi target utama serigala.'
  },
  {
    id: 'sheriff',
    isBack: false,
    roleClass: 'role-sheriff',
    faction: 'ALLIANCE',
    serial: 'TKT·SF·11',
    titleEn: 'SHERIFF',
    titleId: 'Sang Sheriff',
    quote: '\"Bintang lencana ini bukan hiasan. Di karnaval ini, <span>hukum tetap berlaku</span> — bahkan untuk hantu sekalipun.\"',
    abilityTitle: 'EKSEKUSI HUKUM (SIANG)',
    abilityDesc: 'Sekali per permainan di fase siang: Tembak mati 1 pemain tanpa perlu vote. Namun jika sasarannya <b>Warga biasa</b>, kamu kehilangan bintang lencana selamanya.'
  },
  {
    id: 'villager-1',
    isBack: false,
    roleClass: 'role-villager-1',
    faction: 'ALLIANCE',
    serial: 'TKT·VL·12',
    titleEn: 'VILLAGER',
    titleId: 'Warga Biasa',
    quote: '\"Aku hanya penjual karcis. Tapi percayalah <span>insting wargaku</span> tak pernah bohong di karnaval ini!\"',
    abilityTitle: 'SUARA RAKYAT (SIANG)',
    abilityDesc: 'Tidak ada kemampuan khusus. Andalkan <b>logika & diskusi</b> siang hari untuk menemukan dan mengeksekusi Serigala bersama warga lainnya.'
  },
  {
    id: 'villager-2',
    isBack: false,
    roleClass: 'role-villager-2',
    faction: 'ALLIANCE',
    serial: 'TKT·VL·13',
    titleEn: 'VILLAGER',
    titleId: 'Warga Biasa',
    quote: '\"Aku hanya tukang balon. Tapi kalau ketemu serigala, <span>balon ini kutusukkan</span> tepat di mukanya!\"',
    abilityTitle: 'SUARA RAKYAT (SIANG)',
    abilityDesc: 'Tidak ada kemampuan khusus. Andalkan <b>logika & diskusi</b> siang hari untuk menemukan dan mengeksekusi Serigala bersama warga lainnya.'
  },
  {
    id: 'villager-3',
    isBack: false,
    roleClass: 'role-villager-3',
    faction: 'ALLIANCE',
    serial: 'TKT·VL·14',
    titleEn: 'VILLAGER',
    titleId: 'Warga Biasa',
    quote: '\"Aku pemain akrobat. Kalau perlu aku salto sambil bawa obor <span>untuk membakar serigala.</span>\"',
    abilityTitle: 'SUARA RAKYAT (SIANG)',
    abilityDesc: 'Tidak ada kemampuan khusus. Andalkan <b>logika & diskusi</b> siang hari untuk menemukan dan mengeksekusi Serigala bersama warga lainnya.'
  },
  {
    id: 'werewolf-2',
    isBack: false,
    roleClass: 'role-werewolf-2',
    faction: 'SHADOWS',
    serial: 'TKT·WW·15',
    titleEn: 'WEREWOLF',
    titleId: 'Serigala Kawanan',
    quote: '\"Aku bukan penampil utama. Aku hanya <span>bayangan yang menerkam</span> saat lampu dipadamkan.\"',
    abilityTitle: 'NALURI PEMANGSA (MALAM)',
    abilityDesc: 'Bangun bersama kawananmu saat malam. Diskusikan dan pilih <b>1 mangsa</b> untuk dicabik-cabik dari arena permainan.'
  },
  {
    id: 'lone-wolf',
    isBack: false,
    roleClass: 'role-lone-wolf',
    faction: 'SHADOWS',
    serial: 'TKT·LW·16',
    titleEn: 'LONE WOLF',
    titleId: 'Serigala Penyendiri',
    quote: '\"Kawanan? Itu beban. Aku berburu sendirian dan akan <span>memenangkan karnaval ini</span> seorang diri.\"',
    abilityTitle: 'FERAL HUNT (MALAM)',
    abilityDesc: 'Bermain sendiri tanpa kawanan. Menang jika hanya tersisa <b>dirimu dan 1 pemain lain</b>. Tiap malam, pilih 1 mangsa secara mandiri.'
  },
  {
    id: 'doppelganger',
    isBack: false,
    roleClass: 'role-doppelganger',
    faction: 'CHAOS',
    serial: 'TKT·DG·17',
    titleEn: 'DOPPELGANGER',
    titleId: 'Sang Penjiplak',
    quote: '\"Wajahku adalah wajahmu. Mimpimu adalah mimpiku. Di karnaval ini, <span>hanya ada satu dari kita</span> yang asli.\"',
    abilityTitle: 'CERMIN JIWA (MALAM 1)',
    abilityDesc: 'Malam pertama: Pilih 1 pemain. Lihat kartu rolenya. <b>Salin identitasnya</b> saat ia meninggal — kamu menggantikan role dan tujuan menangnya!'
  },
  {
    id: 'serial-killer',
    isBack: false,
    roleClass: 'role-serial-killer',
    faction: 'CHAOS',
    serial: 'TKT·SK·18',
    titleEn: 'SERIAL KILLER',
    titleId: 'Pembunuh Berantai',
    quote: '\"Serigala, Warga — semua sama saja bagiku. Karnaval ini berakhir <span>ketika hanya aku yang berdiri.</span>\"',
    abilityTitle: 'PISAU MALAM (MALAM)',
    abilityDesc: 'Setiap malam: Bunuh <b>1 pemain pilihanmu</b> secara diam-diam. Menang jika menjadi satu-satunya penyintas. Kebal terhadap serangan serigala.'
  },
  {
    id: 'idiot',
    isBack: false,
    roleClass: 'role-idiot',
    faction: 'ALLIANCE',
    serial: 'TKT·ID·19',
    titleEn: 'IDIOT',
    titleId: 'Si Culun',
    quote: '\"Hei! Kenapa semua orang marah padaku? Aku cuma... eh, <span>aku mau bilang sesuatu...</span> eh, lupa.\"',
    abilityTitle: 'PERLINDUNGAN KENAIFAN',
    abilityDesc: 'Jika kamu divoting untuk dieksekusi dan identitasmu terungkap, kamu <b>tidak jadi mati</b> — tapi selamanya kehilangan hak untuk vote.'
  },
  {
    id: 'prince',
    isBack: false,
    roleClass: 'role-prince',
    faction: 'ALLIANCE',
    serial: 'TKT·PC·20',
    titleEn: 'PRINCE',
    titleId: 'Sang Pangeran',
    quote: '\"Aku tidak memerlukan bodyguard di karnaval ini. Darah ningratku sendiri yang akan <span>membuatku tetap hidup.</span>\"',
    abilityTitle: 'DARAH NINGRAT',
    abilityDesc: 'Jika kamu divoting pertama kali untuk dieksekusi oleh warga, vote itu <b>otomatis gagal</b> dan identitasmu terungkap. Kekebalan ini hanya berlaku <b>sekali</b>.'
  },
  {
    id: 'little-girl',
    isBack: false,
    roleClass: 'role-little-girl',
    faction: 'ALLIANCE',
    serial: 'TKT·LG·21',
    titleEn: 'LITTLE GIRL',
    titleId: 'Gadis Kecil',
    quote: '\"Ssst... aku bisa melihat lewat celah jari tanganku. <span>Aku tau siapa kamu,</span> serigala jahat.\"',
    abilityTitle: 'MATA CELAH (MALAM)',
    abilityDesc: 'Kamu boleh curi-curi melihat saat Serigala bangun di malam hari. Jika <b>ketahuan</b> oleh Serigala yang melihatmu mengintip, kamu langsung <b>mati malam itu!</b>'
  },
  {
    id: 'back',
    isBack: true,
    roleClass: 'role-back'
  }
];
