const popartDeckData = [
    {
        "id": "seer",
        "themeClass": "t-seer",
        "facBadge": "ALLIANCE",
        "codeBadge": "SER-09",
        "titleId": "PENERAWANG",
        "titleEn": "The Oracle",
        "ability": "MATA BATIN FAKTA",
        "quote": "\"Mata ketigaku tidak pernah berbohong, sayang! Aku tahu rahasiamu!\"",
        "desc": "Tunjuk satu pemain di malam hari. Moderator akan membocorkan identitas aslinya: apakah\n                    ia <b>Serigala</b> atau bukan. Pandu warga dengan bukti, tapi awas jangan sampai ketahuan serigala!"
    },
    {
        "id": "hunter",
        "themeClass": "t-hunter",
        "facBadge": "VIGILANTE",
        "codeBadge": "HNT-77",
        "titleId": "PEMBURU",
        "titleEn": "The Marksman",
        "ability": "TEMBAKAN TERAKHIR",
        "quote": "\"Bawa aku ke neraka, dan akan kutarik satu monster bersamaku!\"",
        "desc": "Jika kau terbunuh oleh serigala atau dieksekusi paksa di siang hari, kau memiliki hak\n                    mutlak untuk <b>menembak mati</b> satu pemain pilihanmu secara instan sebelum kau menghembuskan\n                    napas terakhir."
    },
    {
        "id": "wolf",
        "themeClass": "t-wolf",
        "facBadge": "SHADOWS",
        "codeBadge": "WW-00X",
        "titleId": "SERIGALA",
        "titleEn": "The Predator",
        "ability": "INSTING MEMBUNUH",
        "quote": "\"Senyum paling manis di siang hari, taring paling tajam di malam hari! GRRRR!\"",
        "desc": "Bangun di malam hari. Berkomunikasi dengan serigala lain untuk <b>mencabik satu\n                        korban</b> tanpa ampun. Menyamarlah jadi warga di siang hari. Kau menang jika jumlah serigala\n                    sama dengan sisa warga!"
    },
    {
        "id": "jester",
        "themeClass": "t-jester",
        "facBadge": "CHAOS",
        "codeBadge": "ERR-404",
        "titleId": "SI BADUT",
        "titleEn": "The Trickster",
        "ability": "TAWA KEMATIAN",
        "quote": "\"Ayo, gantung aku! Bikin aku terbang tinggi dan kita lihat siapa yang tertawa!\"",
        "desc": "Kematianmu adalah kemenanganmu! Bertingkahlah gila, manipulasi warga agar mereka\n                    menuduh lalu <b>mengeksekusimu</b> di pengadilan siang hari. Jika digantung, kau memenangkan\n                    permainan seorang diri!"
    },
    {
        "id": "guard",
        "themeClass": "t-guard",
        "facBadge": "ALLIANCE",
        "codeBadge": "GRD-01",
        "titleId": "PELINDUNG",
        "titleEn": "The Aegis",
        "ability": "PERISAI ILAHI",
        "quote": "\"Malam ini tidak ada darah yang tumpah di bawah pengawasanku! MINGGIR!\"",
        "desc": "Pilih satu pemain setiap malam untuk kau jaga. Jika ia diserang serigala, <b>ia akan\n                        selamat</b>. Kau boleh menjaga dirimu sendiri, tapi tidak boleh menjaga orang yang sama dua\n                    malam berturut-turut!"
    },
    {
        "id": "mod",
        "themeClass": "t-mod",
        "facBadge": "GOD MODE",
        "codeBadge": "MOD-00",
        "titleId": "MODERATOR",
        "titleEn": "The Almighty",
        "ability": "KUASA MUTLAK",
        "quote": "\"Saya yang memimpin. Tidak ada diskusi. DIAM SEMUA!\"",
        "desc": "Moderator tahu <b>semua identitas</b>. Pimpin jalannya malam & siang, sampaikan hasil\n                    serangan, dan jaga agar permainan berjalan adil. Kamu bukan pemain — kamu adalah <b>Tuhan</b>-nya\n                    permainan ini."
    },
    {
        "id": "alpha_wolf",
        "themeClass": "t-alphawolf",
        "facBadge": "SHADOWS",
        "codeBadge": "AW-001",
        "titleId": "ALPHA WOLF",
        "titleEn": "The Apex Predator",
        "ability": "PERINTAH KAWANAN",
        "quote": "\"Kau bukan serigala. Kau adalah dewa malam yang sedang lapar!\"",
        "desc": "Sebagai pemimpin, setiap malam kau memimpin kawanan untuk <b>memilih korban</b>.\n                    Keputusanmu final dan mutlak. Selain itu, kau dapat <b>merekrut</b> 1 warga menjadi serigala sekali\n                    sepanjang permainan!"
    },
    {
        "id": "cupid",
        "themeClass": "t-cupid",
        "facBadge": "NEUTRAL",
        "codeBadge": "CPD-69",
        "titleId": "CUPID",
        "titleEn": "The Love Assassin",
        "ability": "CINTA MEMATIKAN",
        "quote": "\"Kupertemukan dua jiwamu. Tapi kalau satunya mati... kalian berdua ikut!\"",
        "desc": "Di malam pertama, tunjuk <b>2 pemain</b> sebagai sepasang kekasih. Jika salah satu\n                    mati, yang lain ikut mati karena patah hati. Jika keduanya adalah musuh, mereka kini punya misi\n                    baru: bertahan hidup bersama!"
    },
    {
        "id": "witch",
        "themeClass": "t-witch",
        "facBadge": "ALLIANCE",
        "codeBadge": "WTC-13",
        "titleId": "PENYIHIR",
        "titleEn": "The Brew Master",
        "ability": "RAMUAN RAHASIA",
        "quote": "\"Kuberi warna hijau: kau selamat. Kuberi warna ungu: kau tamat!\"",
        "desc": "Punya <b>2 ramuan</b> sekali pakai: <b>Racun</b> untuk membunuh 1 target malam ini,\n                    atau <b>Antidot</b> untuk menyelamatkan korban serangan serigala malam ini. Masing-masing hanya bisa\n                    dipakai sekali!"
    },
    {
        "id": "wizard",
        "themeClass": "t-wizard",
        "facBadge": "ALLIANCE",
        "codeBadge": "WZD-77",
        "titleId": "PENYIHIR TUA",
        "titleEn": "The Arcane Master",
        "ability": "PEREDAM MANTRA",
        "quote": "\"Diam! Malam ini kemampuanmu tidak ada artinya di hadapanku!\"",
        "desc": "Setiap malam, pilih satu pemain untuk <b>dibungkam</b>. Pemain itu tidak dapat\n                    menggunakan kemampuan spesialnya malam ini. Serigala? Tidak bisa menyerang. Guardian? Tidak bisa\n                    melindungi. Seer? Tidak bisa melihat!"
    },
    {
        "id": "veteran",
        "themeClass": "t-veteran",
        "facBadge": "ALLIANCE",
        "codeBadge": "VET-01",
        "titleId": "VETERAN",
        "titleEn": "The War Machine",
        "ability": "SIAGA TEMPUR",
        "quote": "\"Coba serang aku malam ini. Aku sudah menunggu sejak Vietnam!\"",
        "desc": "Pilih untuk <b>berjaga</b> di suatu malam. Jika diserang serigala saat berjaga,\n                    serigala itulah yang mati! Tapi kemampuan ini hanya bisa dipakai <b>1 kali</b> seluruh permainan.\n                    Gunakan dengan bijak!"
    },
    {
        "id": "card_back",
        "themeClass": "t-back",
        "facBadge": "",
        "codeBadge": "WEREWOLF : POP-ART",
        "titleId": "MRSETIAWAN",
        "titleEn": "KARTU BELAKANG",
        "ability": "",
        "quote": "",
        "desc": ""
    },
    {
        "id": "bodyguard",
        "themeClass": "t-bodyguard",
        "facBadge": "ALLIANCE",
        "codeBadge": "BDG-99",
        "titleId": "BODYGUARD",
        "titleEn": "The Sacrifice",
        "ability": "TAMENG MANUSIA",
        "quote": "\"Tubuhku adalah pelurumu. Aku tidak akan membiarkanmu mati malam ini!\"",
        "desc": "Pilih 1 pemain untuk dijaga tiap malam. Jika ia diserang serigala, <b>kamu yang mati menggantikannya</b>. Berbeda dari Guardian — kamu tidak kebal, tapi mengorbankan dirimu sendiri!"
    },
    {
        "id": "priest",
        "themeClass": "t-priest",
        "facBadge": "ALLIANCE",
        "codeBadge": "PRS-01",
        "titleId": "PASTOR",
        "titleEn": "The Divine Shepherd",
        "ability": "AIR SUCI",
        "quote": "\"Ku siramkan kebenaran ini ke wajahmu. Kalau kau serigala... selamat tinggal!\"",
        "desc": "Sekali per permainan, <b>siramkan air suci</b> ke satu pemain di siang hari. Jika ia <b>serigala → serigala itu mati</b>. Jika ia warga biasa → <b>kamu yang mati</b>. Gunakan dengan penuh keyakinan!"
    },
    {
        "id": "mayor",
        "themeClass": "t-mayor",
        "facBadge": "ALLIANCE",
        "codeBadge": "MYR-01",
        "titleId": "WALIKOTA",
        "titleEn": "The Double Vote",
        "ability": "SUARA GANDA",
        "quote": "\"Satu suaraku sama dengan dua suaramu. Itu namanya demokrasi!\"",
        "desc": "Identitasmu rahasia. Kau dapat <b>mengungkap dirimu</b> kapan saja untuk mengaktifkan <b>suara ganda</b> dalam voting eksekusi siang hari. Jika kau mati, warga mendapat satu sesi voting darurat!"
    },
    {
        "id": "sheriff",
        "themeClass": "t-sheriff",
        "facBadge": "ALLIANCE",
        "codeBadge": "SHF-44",
        "titleId": "SHERIFF",
        "titleEn": "The Law Maker",
        "ability": "TEMBAK MATI",
        "quote": "\"Aku hukum dan aku eksekutornya.\"",
        "desc": "Memiliki satu pistol dengan <b>1 peluru mematikan</b>. Pilih 1 target di malam hari untuk ditembak mati. Jika yang kamu tembak adalah penduduk desa biasa, kamu akan <b>mati bunuh diri</b> karena rasa bersalah!"
    },
    {
        "id": "vil1",
        "themeClass": "t-vil1",
        "facBadge": "ALLIANCE",
        "codeBadge": "VIL-01",
        "titleId": "WARGA BIASA",
        "titleEn": "The Farmer",
        "ability": "HARAPAN DESA",
        "quote": "\"Ladangku mungkin diam, tapi mataku tidak pernah tidur.\"",
        "desc": "Kamu tidak memiliki kemampuan spesial di malam hari. Tapi suara dan analisamu di siang hari adalah kunci utama kemenangan warga. Bersatulah dan temukan serigala sebelum fajar memerah darah!"
    },
    {
        "id": "vil2",
        "themeClass": "t-vil2",
        "facBadge": "ALLIANCE",
        "codeBadge": "VIL-02",
        "titleId": "WARGA BIASA",
        "titleEn": "The Baker",
        "ability": "HARAPAN DESA",
        "quote": "\"Rotiku hangat, tapi ada yang dingin dari tatapan tetanggaku hari ini.\"",
        "desc": "Kamu tidak memiliki kemampuan spesial di malam hari. Tapi suara dan analisamu di siang hari adalah kunci utama kemenangan warga. Bersatulah dan temukan serigala sebelum fajar memerah darah!"
    },
    {
        "id": "vil3",
        "themeClass": "t-vil3",
        "facBadge": "ALLIANCE",
        "codeBadge": "VIL-03",
        "titleId": "WARGA BIASA",
        "titleEn": "The Blacksmith",
        "ability": "HARAPAN DESA",
        "quote": "\"Baja ditempa dalam panas. Kita ditempa dalam teror ini.\"",
        "desc": "Kamu tidak memiliki kemampuan spesial di malam hari. Tapi suara dan analisamu di siang hari adalah kunci utama kemenangan warga. Bersatulah dan temukan serigala sebelum fajar memerah darah!"
    },
    {
        "id": "werewolf2",
        "themeClass": "t-werewolf-2",
        "facBadge": "WOLF PACK",
        "codeBadge": "WLF-02",
        "titleId": "WEREWOLF",
        "titleEn": "The Apex Predator",
        "ability": "INSTING PEMBURU",
        "quote": "\"Bukan bulan yang memanggilku, tapi bau ketakutan kalian.\"",
        "desc": "Bangun di malam hari bersama serigala lain untuk berdiskusi dan memilih satu korban untuk dibunuh. Identitasmu tetap rahasia di siang hari. Cobalah berbaur agar tidak dicurigai warga!"
    },
    {
        "id": "lone_wolf",
        "themeClass": "t-lonewolf",
        "facBadge": "ALLIANCE?",
        "codeBadge": "LNW-11",
        "titleId": "TERKUTUK",
        "titleEn": "The Lone Wolf",
        "ability": "TERKUTUK",
        "quote": "\"Ada monster yang tertidur di dalam diriku. Jangan bangunkan dia.\"",
        "desc": "Awalnya kau adalah warga biasa. Namun, jika Serigala menyerangmu di malam hari, kamu <b>TIDAK MATI!</b> Kamu akan terbangun berubah menjadi <b>Serigala</b> dan bergabung dengan pihak mereka selamanya."
    },
    {
        "id": "doppelganger",
        "themeClass": "t-doppelganger",
        "facBadge": "UNKNOWN",
        "codeBadge": "DPG-00",
        "titleId": "DOPPELGANGER",
        "titleEn": "The Mimic",
        "ability": "CURI IDENTITAS",
        "quote": "\"Sebuah kehormatan untuk... menjadi dirimu. Selamanya.\"",
        "desc": "Saat malam pertama, pilih satu pemain. Jika pemain tersebut mati kapan pun itu, <b>kamu langsung terbangun menggantikan peran, faksi, dan kekuatannya</b>. Sampai saat itu tiba, kamu tidak memiliki kubu."
    },
    {
        "id": "serial_killer",
        "themeClass": "t-serialkiller",
        "facBadge": "SOLO",
        "codeBadge": "SK-666",
        "titleId": "PEMBUNUH<br>BERANTAI",
        "titleEn": "The Maniac",
        "ability": "MALAM BERDARAH",
        "quote": "\"Serigala membunuh untuk bertahan hidup. Aku? Aku membunuh demi seni.\"",
        "desc": "Setiap malam, kau boleh <b>membunuh 1 pemain</b> secara brutal. Kau kebal dari serangan Serigala karena keberingasanmu. Faksi: <b>SOLO</b> — kau menang bila berhasil selamat hingga menjadi orang terakhir yang ada!"
    },
    {
        "id": "idiot",
        "themeClass": "t-idiot",
        "facBadge": "ALLIANCE",
        "codeBadge": "IDI-0T",
        "titleId": "SANG PANDIR",
        "titleEn": "The Idiot",
        "ability": "KEBAL EJEKAN",
        "quote": "\"Haha! Kalian semua gantung orang yang salah!\"",
        "desc": "Jika wagra desa mem-voting mati dirimu di balai desa, ungkapkan identitasmu! Kamu <b>TIDAK MATI</b> dan dibiarkan hidup. Namun, kamu dianggap gila dan <b>kehilangan hak suara</b> dalam voting hingga game berakhir."
    },
    {
        "id": "prince",
        "themeClass": "t-prince",
        "facBadge": "ALLIANCE",
        "codeBadge": "PRN-01",
        "titleId": "PANGERAN",
        "titleEn": "The Royal Heir",
        "ability": "HAK ISTIMEWA",
        "quote": "\"Berani kalian menyentuh darah biru ini? Aku adalah hukum!\"",
        "desc": "Jika penduduk desa mem-votingmu untuk digantung di siang hari, singkap identitasmu! Hukuman gantungmu <b>dibatalkan otomatis</b>. Hebatnya lagi, wibawamu membuat kamu <b>tetap bisa melakukan voting</b> di kemudian hari, berbeda dari Idiot."
    },
    {
        "id": "little_girl",
        "themeClass": "t-littlegirl",
        "facBadge": "ALLIANCE",
        "codeBadge": "LGL-07",
        "titleId": "GADIS KECIL",
        "titleEn": "The Peeper",
        "ability": "PENGINTIP MALAM",
        "quote": "\"Ssst... aku lihat ada bayangan panjang bertaring di luar jendelaku.\"",
        "desc": "Saat kawanan Serigala bangun, kamu <b>boleh mengintip diam-diam</b> untuk menebak identitas mereka. TAPI HATI-HATI! Jika serigala menunjuk dan menyadari kamu sedang mengintip, kamu akan langsung <b>dibunuh seketika!</b>"
    }
];
