const punksylDeckData = [
    {
        id: 'WLF-00',
        style: '--accent: var(--c-magenta); --title-color: var(--c-yellow); --rot-slash: -5deg; --rot-header: -3deg; --rot-sub: 2deg; --rot-quote: 1deg; --rot-code: -2deg;',
        faction: 'SHADOWS',
        title: 'WERE<br>WOLF',
        subtitle: 'SANG SERIGALA',
        quote: '"KAMI LAPAR. DAN KALIAN TERLIHAT SANGAT LEZAT."',
        descHtml: `<strong>INSTING PEMANGSA:</strong> Bangun setiap malam bersama kawanan. Pilih 1 mangsa untuk dihabisi tanpa ampun. Di siang hari, berbaurlah seperti domba bodoh.`,
        code: 'WLF-00'
    },
    {
        id: 'SER-EYE',
        style: '--accent: var(--c-cyan); --title-color: var(--c-white); --slash-top: -15mm; --rot-slash: 4deg; --rot-header: 2deg; --rot-sub: -3deg; --rot-quote: -1.5deg; --rot-code: 2deg;',
        faction: 'ALLIANCE',
        title: 'THE<br>SEER',
        subtitle: 'SANG PERAMAL',
        quote: '"AKU BISA MELIHAT DOSA-DOSAMU SAAT KAU TERLELAP."',
        descHtml: `<strong>MATA BATIN:</strong> Setiap malam, pilih 1 pemain untuk mengintip wujud aslinya. Bimbing warga menuju kebenaran di siang hari, tanpa membuka kedokmu!`,
        code: 'SER-EYE'
    },
    {
        id: 'HNT-X9',
        style: '--accent: var(--c-green); --title-color: var(--c-yellow); --rot-slash: -7deg; --rot-header: -4deg; --rot-sub: 1deg; --rot-quote: 2deg; --title-size: 24pt;',
        faction: 'VANGUARD',
        title: 'HUNT<br>ER',
        subtitle: 'SANG PEMBURU',
        quote: '"KAU MENGGIGITKU? KUPASTIKAN KEPALAMU MELEDAK."',
        descHtml: `<strong>PELATUK TERAKHIR:</strong> Jika kamu terbunuh (diterkam atau dieksekusi warga), gunakan nafas terakhirmu untuk menarik pelatuk dan menembak mati 1 pemain secara instan.`,
        code: 'HNT-X9'
    },
    {
        id: 'JST-HAHA',
        style: '--accent: var(--c-yellow); --title-color: var(--c-magenta); --rot-slash: 6deg; --rot-header: 3deg; --rot-sub: -4deg; --rot-quote: -2deg; --rot-code: 3deg;',
        faction: 'CHAOS',
        title: 'JES<br>TER',
        subtitle: 'SI BADUT GILA',
        quote: '"AYO GANTUNG AKU! INI AKAN JADI LELUCON TERBAIK!"',
        quoteStyle: 'color: var(--c-magenta);',
        descHtml: `<strong style="color: var(--c-magenta);">KEMENANGAN GILA:</strong> Tujuanmu satu: memanipulasi warga agar mem-voting mati dirimu di siang hari. Jika kamu berhasil digantung, kamu menang mutlak sendirian!`,
        code: 'JST-HAHA',
        codeStyle: 'background: var(--c-magenta); color: var(--c-white);'
    },
    {
        id: 'GRD-DEF',
        style: '--accent: var(--c-orange); --title-color: var(--c-black); --rot-slash: 3deg; --slash-bot: 38mm; --rot-header: -2deg; --rot-sub: 2deg; --rot-quote: 1.5deg; --rot-code: -1deg; --title-size: 21pt;',
        slashStyle: 'background-image: repeating-linear-gradient(45deg, transparent, transparent 5px, rgba(0,0,0,0.2) 5px, rgba(0,0,0,0.2) 10px);',
        faction: 'ALLIANCE',
        title: 'GUAR<br>DIAN',
        titleStyle: 'color: var(--c-white);',
        subtitle: 'SANG PELINDUNG',
        quote: '"BERLINDUNGLAH DI BELAKANGKU, ATAU MATI DI LUAR SANA."',
        descHtml: `<strong>PERISAI ABSOLUT:</strong> Pilih 1 pemain setiap malam. Jika targetmu diserang serigala, dinding perlindunganmu memblokir serangan tersebut total.`,
        code: 'GRD-DEF'
    },
    {
        id: 'MOD-000',
        style: '--accent: var(--c-red); --title-color: var(--c-white); --rot-slash: 2deg; --slash-top: -8mm; --slash-bot: 40mm; --rot-header: 1deg; --rot-sub: -2deg; --rot-quote: 1deg; --rot-code: -1deg; --title-size: 19pt;',
        slashStyle: 'background: linear-gradient(135deg, var(--c-black) 60%, var(--c-red) 100%);',
        faction: 'SOVEREIGN',
        title: 'MODE\u003cbr\u003eRAT\u003cbr\u003eOR',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 var(--c-red), -1px -1px 0 var(--c-red);',
        subtitle: 'TUHAN PERMAINAN',
        subtitleStyle: 'background: var(--c-red); color: var(--c-white);',
        quote: '"DIAM. AKU TIDAK BERMAIN. AKU MENGATUR SEGALANYA."',
        quoteStyle: 'color: var(--c-red);',
        descHtml: `<strong>OMNIPOTENT:</strong> Kamu bukan pemain. Kamu adalah hakim, eksekutor, dan dewa. Kontrol alur malam & siang. Keputusanmu <strong>ABSOLUT</strong> dan tidak bisa digugat.`,
        code: 'MOD-000',
        codeStyle: 'background: var(--c-red); color: var(--c-white);'
    },
    {
        id: 'ALF-REX',
        style: '--accent: var(--c-purple); --title-color: var(--c-yellow); --rot-slash: -6deg; --rot-header: -3deg; --rot-sub: 3deg; --rot-quote: 2deg; --rot-code: -3deg; --title-size: 18pt;',
        slashStyle: 'background: linear-gradient(120deg, var(--c-purple) 40%, #1a0033 100%); clip-path: polygon(0 0, 100% 0, 100% 70%, 0 95%);',
        faction: 'SHADOWS',
        title: 'ALPHA\u003cbr\u003eWOLF',
        subtitle: 'PEMIMPIN KAWANAN',
        quote: '"KAWANAN TUNDUK PADAKU. MANGSAMU ADALAH YANG KUBIDIK."',
        descHtml: `<strong>DOMINASI KAWANAN:</strong> Tiap malam, kamu menentukan target serangan kawanan. Jika kamu mati, kawanan kehilangan 1 serangan giliran berikutnya. <strong>Kamu kebal dari ramalan Peramal.</strong>`,
        code: 'ALF-REX',
        codeStyle: 'background: var(--c-purple); color: var(--c-white);'
    },
    {
        id: 'CPD-LUV',
        style: '--accent: var(--c-magenta); --title-color: var(--c-magenta); --rot-slash: 7deg; --slash-top: -12mm; --slash-bot: 44mm; --rot-header: 3deg; --rot-sub: -3deg; --rot-quote: -2deg; --rot-code: 2deg; --title-size: 20pt;',
        slashStyle: 'background: linear-gradient(110deg, #ff69b4 0%, var(--c-magenta) 60%, #8b0057 100%);',
        faction: 'CHAOS',
        title: 'CU\u003cbr\u003ePID',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #8b0057, -1px -1px 0 #8b0057;',
        subtitle: 'PANAH CINTA GILA',
        subtitleStyle: 'background: #8b0057; color: #ff69b4;',
        quote: '"CINTAMU ADALAH PENJARA. DAN AKU YANG MENUTUP PINTUNYA."',
        quoteStyle: 'color: var(--c-magenta);',
        descHtml: `<strong>IKAT JIWA:</strong> Malam pertama, pilih 2 pemain — mereka terikat selamanya. Jika 1 mati, yang lain ikut mati. Jika keduanya bertahan hingga akhir, <strong>mereka menang bersama</strong>.`,
        code: 'CPD-LUV',
        codeStyle: 'background: var(--c-magenta); color: var(--c-white);'
    },
    {
        id: 'WTC-HEX',
        style: '--accent: var(--c-green); --title-color: var(--c-yellow); --rot-slash: -4deg; --slash-bot: 39mm; --rot-header: -2deg; --rot-sub: 2deg; --rot-quote: 1.5deg; --rot-code: -2deg; --title-size: 20pt;',
        slashStyle: 'background: linear-gradient(130deg, #003300 0%, var(--c-green) 50%, #001a00 100%);',
        faction: 'CHAOS',
        title: 'WIT\u003cbr\u003eCH',
        subtitle: 'DUKUN JALANAN',
        subtitleStyle: 'background: #003300; color: var(--c-green);',
        quote: '"DUA RAMUAN. SATU MEMBUNUH. SATU MENGHIDUPKAN. PILIHANMU."',
        quoteStyle: 'color: var(--c-green);',
        descHtml: `<strong>RAMUAN GANDA:</strong> Kamu punya 2 ramuan, sekali pakai seumur game. <strong>Racun</strong>: bunuh 1 pemain saat malam. <strong>Antidot</strong>: selamatkan target kawanan malam ini secara instan.`,
        code: 'WTC-HEX',
        codeStyle: 'background: #003300; color: var(--c-green); border-color: var(--c-green);'
    },
    {
        id: 'WZD-ARC',
        style: '--accent: var(--c-cyan); --title-color: var(--c-cyan); --rot-slash: 5deg; --slash-top: -10mm; --slash-bot: 41mm; --rot-header: 2deg; --rot-sub: -3deg; --rot-quote: -1deg; --rot-code: 2deg; --title-size: 19pt;',
        slashStyle: 'background: linear-gradient(115deg, #001f3f 0%, #0050a0 55%, var(--c-cyan) 100%);',
        faction: 'ALLIANCE',
        title: 'WIZ<br>ARD',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #001f3f, -1px -1px 0 var(--c-cyan);',
        subtitle: 'HACKER MISTIK',
        subtitleStyle: 'background: #001f3f; color: var(--c-cyan);',
        quote: '"DUNIA INI HANYALAH KODE. DAN AKU SUDAH PUNYA ROOT ACCESS."',
        quoteStyle: 'color: var(--c-cyan);',
        descHtml: `<strong>MANTRA INTERVENSI:</strong> Sekali per game, pilih 1 aksi malam — blokir total kemampuan target atau redirect serangan kawanan ke pemain lain pilihanmu.`,
        code: 'WZD-ARC',
        codeStyle: 'background: #001f3f; color: var(--c-cyan); border-color: var(--c-cyan);'
    },
    {
        id: 'VET-WAR',
        style: '--accent: var(--c-orange); --title-color: var(--c-white); --rot-slash: -8deg; --slash-top: -5mm; --slash-bot: 37mm; --rot-header: -4deg; --rot-sub: 3deg; --rot-quote: 2deg; --rot-code: -3deg; --title-size: 18pt;',
        slashStyle: 'background: repeating-linear-gradient(-45deg, #3d2200, #3d2200 8px, var(--c-orange) 8px, var(--c-orange) 16px);',
        faction: 'VANGUARD',
        title: 'VET<br>ERAN',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #3d2200, -1px -1px 0 var(--c-orange);',
        subtitle: 'PEJUANG TRAUMA',
        subtitleStyle: 'background: #3d2200; color: var(--c-orange);',
        quote: '"AKU SUDAH MATI BERKALI-KALI. SEKALI LAGI BUKAN MASALAH."',
        quoteStyle: 'color: var(--c-orange);',
        descHtml: `<strong>SIAGA TEMPUR:</strong> Umumkan "SIAGA" saat siang. Malam itu, siapapun yang menyerangmu akan TERBUNUH balik — termasuk warga atau serigala. Bisa dipakai <strong>3x</strong>.`,
        code: 'VET-WAR',
        codeStyle: 'background: #3d2200; color: var(--c-orange); border-color: var(--c-orange);'
    },
    {
        id: 'BGD-IRON',
        style: '--accent: var(--c-cyan); --title-color: var(--c-black); --rot-slash: -3deg; --slash-top: -6mm; --slash-bot: 40mm; --rot-header: -2deg; --rot-sub: 3deg; --rot-quote: 1deg; --rot-code: -2deg; --title-size: 18pt;',
        slashStyle: 'background: linear-gradient(125deg, #b0bec5 0%, #607d8b 50%, #263238 100%);',
        faction: 'ALLIANCE',
        title: 'BODY<br>GUARD',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #263238, -1px -1px 0 var(--c-black);',
        subtitle: 'TEMBOK HIDUP',
        subtitleStyle: 'background: #263238; color: var(--c-cyan);',
        quote: '"TIDAK ADA YANG LEWAT. BAHKAN PELURU PUN TIDAK."',
        quoteStyle: 'color: var(--c-cyan);',
        descHtml: `<strong>PERISAI DIRI:</strong> Setiap malam, pilih 1 pemain untuk dilindungi. Jika diserang, <strong>kamu yang mati menggantikan mereka</strong>. Tapi kamu tidak bisa melindungi orang yang sama dua malam berturut-turut.`,
        code: 'BGD-IRON',
        codeStyle: 'background: #263238; color: var(--c-cyan); border-color: var(--c-cyan);'
    },
    {
        id: 'PRS-HOLY',
        style: '--accent: var(--c-yellow); --title-color: var(--c-white); --rot-slash: 4deg; --slash-top: -8mm; --slash-bot: 38mm; --rot-header: 2deg; --rot-sub: -2deg; --rot-quote: -1.5deg; --rot-code: 1deg; --title-size: 20pt;',
        slashStyle: 'background: linear-gradient(110deg, #3d2200 0%, #8b6914 50%, var(--c-yellow) 100%);',
        faction: 'ALLIANCE',
        title: 'PRI<br>EST',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #3d2200, -1px -1px 0 #8b6914;',
        subtitle: 'PENDETA JALANAN',
        subtitleStyle: 'background: #3d2200; color: var(--c-yellow);',
        quote: '"TUHAN BERBISIK PADAKU. DIA MENYEBUT NAMAMU."',
        quoteStyle: 'color: var(--c-yellow);',
        descHtml: `<strong>BAPTIS PERLINDUNGAN:</strong> Sekali per game, berikan <strong>perlindungan suci</strong> pada 1 pemain \u2014 mereka kebal dari segala serangan malam selama 2 giliran penuh.`,
        code: 'PRS-HOLY',
        codeStyle: 'background: #3d2200; color: var(--c-yellow); border-color: var(--c-yellow);'
    },
    {
        id: 'MYR-VOTE',
        style: '--accent: var(--c-red); --title-color: var(--c-white); --rot-slash: 5deg; --slash-top: -10mm; --slash-bot: 42mm; --rot-header: 3deg; --rot-sub: -2deg; --rot-quote: -1deg; --rot-code: 2deg; --title-size: 20pt;',
        slashStyle: 'background: linear-gradient(118deg, #1a0000 0%, #8b0000 55%, var(--c-red) 100%);',
        faction: 'SOVEREIGN',
        title: 'MAY<br>OR',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #1a0000, -1px -1px 0 #8b0000;',
        subtitle: 'WALI KOTA BUSUK',
        subtitleStyle: 'background: #1a0000; color: var(--c-red);',
        quote: '"SUARAMU? MILIKKU. HIDUPMU? JUGA MILIKKU."',
        quoteStyle: 'color: var(--c-red);',
        descHtml: `<strong>VETO ABSOLUT:</strong> Suaramu bernilai <strong>2 vote</strong> saat eksekusi siang. Jika kamu mati dan identitasmu terungkap, warga mendapat <strong>bonus vote</strong> ekstra siang berikutnya.`,
        code: 'MYR-VOTE',
        codeStyle: 'background: #1a0000; color: var(--c-red); border-color: var(--c-red);'
    },
    {
        id: 'SHR-BANG',
        style: '--accent: var(--c-yellow); --title-color: var(--c-black); --rot-slash: -6deg; --slash-top: -8mm; --slash-bot: 38mm; --rot-header: -3deg; --rot-sub: 3deg; --rot-quote: 2deg; --rot-code: -2deg; --title-size: 18pt;',
        slashStyle: 'background: repeating-linear-gradient(60deg, #b8860b, #b8860b 10px, var(--c-yellow) 10px, var(--c-yellow) 20px);',
        faction: 'VANGUARD',
        title: 'SHER<br>IFF',
        titleStyle: 'color: var(--c-black); text-shadow: 1px 1px 0 #b8860b;',
        subtitle: 'PENEGAK HUKUM',
        subtitleStyle: 'background: var(--c-black); color: var(--c-yellow);',
        quote: '"DI KOTA INI, AKU ADALAH HUKUM. DAN HUKUM TIDAK TIDUR."',
        quoteStyle: 'color: #b8860b;',
        descHtml: `<strong>INVESTIGASI LAPANGAN:</strong> Setiap malam, tembak 1 pemain. Jika dia Serigala, dia <strong>terluka parah</strong> (skip giliran berikutnya). Jika bukan, <strong>kamu mati</strong>.`,
        code: 'SHR-BANG',
        codeStyle: 'background: var(--c-black); color: var(--c-yellow); border-color: #b8860b;'
    },
    {
        id: 'VLG-001',
        style: '--accent: var(--c-cyan); --title-color: var(--c-black); --rot-slash: 3deg; --slash-top: -8mm; --slash-bot: 43mm; --rot-header: 2deg; --rot-sub: -2deg; --rot-quote: 1deg; --rot-code: -1deg; --title-size: 20pt;',
        slashStyle: 'background: linear-gradient(105deg, #e0f7fa 0%, var(--c-cyan) 60%, #006064 100%);',
        faction: 'ALLIANCE',
        title: 'VILL<br>AGER',
        titleStyle: 'color: var(--c-black); text-shadow: 1px 1px 0 #006064;',
        subtitle: 'SI TUKANG KETOK',
        subtitleStyle: 'background: #006064; color: var(--c-cyan);',
        quote: '"AKU HANYA WARGA BIASA. PERCAYAI AKU. PLEASE."',
        quoteStyle: 'color: #006064;',
        descHtml: `<strong>INSTING MASSA:</strong> Kamu tak punya kekuatan khusus \u2014 tapi suaramu di siang hari bisa menentukan segalanya. <strong>Temukan serigala. Selamatkan kota. Bertahan hidup.</strong>`,
        code: 'VLG-001',
        codeStyle: 'background: #006064; color: var(--c-cyan); border-color: var(--c-cyan);'
    },
    {
        id: 'VLG-002',
        style: '--accent: var(--c-magenta); --title-color: var(--c-black); --rot-slash: -5deg; --slash-top: -6mm; --slash-bot: 41mm; --rot-header: -2deg; --rot-sub: 3deg; --rot-quote: -1.5deg; --rot-code: 2deg; --title-size: 20pt;',
        slashStyle: 'background: linear-gradient(120deg, #fce4ec 0%, var(--c-magenta) 55%, #880e4f 100%);',
        faction: 'ALLIANCE',
        title: 'VILL<br>AGER',
        titleStyle: 'color: var(--c-black); text-shadow: 1px 1px 0 #880e4f;',
        subtitle: 'SI PARANOID',
        subtitleStyle: 'background: #880e4f; color: #fce4ec;',
        quote: '"KALIAN SEMUA MENCURIGAKAN. TERMASUK KAMU YANG BACA INI."',
        quoteStyle: 'color: var(--c-magenta);',
        descHtml: `<strong>PARANOIA TINGGI:</strong> Kamu tak punya kemampuan khusus \u2014 hanya naluri dan rasa curiga. <strong>Gunakan itu. Salah satu dari mereka pasti serigala.</strong> Mungkin yang diam-diam.`,
        code: 'VLG-002',
        codeStyle: 'background: #880e4f; color: #fce4ec; border-color: var(--c-magenta);'
    },
    {
        id: 'VLG-003',
        style: '--accent: var(--c-orange); --title-color: var(--c-black); --rot-slash: 6deg; --slash-top: -9mm; --slash-bot: 40mm; --rot-header: 3deg; --rot-sub: -3deg; --rot-quote: 2deg; --rot-code: -2deg; --title-size: 20pt;',
        slashStyle: 'background: linear-gradient(112deg, #fff3e0 0%, var(--c-orange) 55%, #bf360c 100%);',
        faction: 'ALLIANCE',
        title: 'VILL<br>AGER',
        titleStyle: 'color: var(--c-black); text-shadow: 1px 1px 0 #bf360c;',
        subtitle: 'SI PEMANTIK',
        subtitleStyle: 'background: #bf360c; color: #fff3e0;',
        quote: '"SERIGALA? AKU SUDAH TAHU DARI TADI. KALIAN HANYA LAMBAT."',
        quoteStyle: 'color: #bf360c;',
        descHtml: `<strong>NALURI JALANAN:</strong> Kamu tak punya kemampuan malam \u2014 tapi kamu jago <strong>membakar massa</strong>. Satu argumen yang tepat bisa mengubah voting siang sepenuhnya.`,
        code: 'VLG-003',
        codeStyle: 'background: #bf360c; color: #fff3e0; border-color: var(--c-orange);'
    },
    {
        id: 'WLF-02',
        style: '--accent: var(--c-red); --title-color: var(--c-yellow); --rot-slash: -8deg; --slash-top: -6mm; --slash-bot: 36mm; --rot-header: -4deg; --rot-sub: 3deg; --rot-quote: 2deg; --rot-code: -3deg;',
        slashStyle: 'background: linear-gradient(130deg, #1a0000 0%, #8b0000 45%, var(--c-red) 100%); clip-path: polygon(0 0, 100% 0, 100% 75%, 0 95%);',
        faction: 'SHADOWS',
        title: 'WERE<br>WOLF',
        subtitle: 'SERIGALA KOTA',
        subtitleStyle: 'background: #1a0000; color: var(--c-red);',
        quote: '"MEREKA MENGIRA AKU TIDUR. AKU SEDANG MENGHITUNG MANGSA."',
        quoteStyle: 'color: var(--c-red);',
        descHtml: `<strong>INSTING PEMANGSA:</strong> Bangun setiap malam bersama kawanan. Pilih 1 mangsa untuk dihabisi. Di siang hari \u2014 <strong>berbaurlah. Menggigit. Bersembunyi. Menang.</strong>`,
        code: 'WLF-02',
        codeStyle: 'background: #1a0000; color: var(--c-red); border-color: var(--c-red);'
    },
    {
        id: 'LWF-SOL',
        style: '--accent: var(--c-white); --title-color: var(--c-white); --rot-slash: -9deg; --slash-top: -5mm; --slash-bot: 35mm; --rot-header: -4deg; --rot-sub: 4deg; --rot-quote: 2.5deg; --rot-code: -3deg; --title-size: 18pt;',
        slashStyle: 'background: linear-gradient(140deg, #0d0d0d 0%, #2a2a2a 50%, #555 100%);',
        faction: 'SOLO',
        factionStyle: 'color: #aaa;',
        title: 'LONE<br>WOLF',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #333, -1px -1px 0 #555;',
        subtitle: 'SERIGALA TERBUANG',
        subtitleStyle: 'background: #0d0d0d; color: #aaa;',
        quote: '"KAWANAN MEMBUANGKU. SEKARANG AKU BERBURU SENDIRIAN."',
        quoteStyle: 'color: #aaa;',
        descHtml: `<strong>PENYENDIRI MEMATIKAN:</strong> Kamu bukan bagian kawanan. Mainkan sendiri. Menangkan sendiri. <strong>Kondisi menang:</strong> jadilah satu-satunya pemain hidup \u2014 atau bunuh semua serigala lain sebelum kamu dieksekusi.`,
        code: 'LWF-SOL',
        codeStyle: 'background: #0d0d0d; color: #aaa; border-color: #555;'
    },
    {
        id: 'DPG-COPY',
        style: '--accent: var(--c-purple); --title-color: var(--c-white); --rot-slash: 5deg; --slash-top: -10mm; --slash-bot: 39mm; --rot-header: 2deg; --rot-sub: -3deg; --rot-quote: -1.5deg; --rot-code: 2deg; --title-size: 16pt;',
        slashStyle: 'background: linear-gradient(115deg, #1a0033 0%, #4a0080 50%, var(--c-purple) 100%);',
        faction: 'CHAOS',
        title: 'DOPPEL<br>GANGER',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #1a0033, -1px -1px 0 var(--c-purple);',
        subtitle: 'SANG PENIRU',
        subtitleStyle: 'background: #1a0033; color: var(--c-purple);',
        quote: '"AKU BUKAN KAMU. TAPI AKU BISA MENJADI KAMU. SEKARANG."',
        quoteStyle: 'color: var(--c-purple);',
        descHtml: `<strong>CERMIN JIWA:</strong> Malam pertama, intip 1 pemain. Jika mereka mati, <strong>kamu mengambil peran mereka sepenuhnya</strong>  \u2014 kemampuan, fraksi, dan kondisi menang mereka jadi milikmu.`,
        code: 'DPG-COPY',
        codeStyle: 'background: #1a0033; color: var(--c-purple); border-color: var(--c-purple);'
    },
    {
        id: 'SKL-KILL',
        style: '--accent: var(--c-red); --title-color: var(--c-white); --rot-slash: -7deg; --slash-top: -5mm; --slash-bot: 34mm; --rot-header: -4deg; --rot-sub: 4deg; --rot-quote: 2deg; --rot-code: -3deg; --title-size: 16pt;',
        slashStyle: 'background: linear-gradient(145deg, #0a0000 0%, #3d0000 40%, #8b0000 75%, var(--c-red) 100%);',
        faction: 'SOLO',
        factionStyle: 'color: #ff6666;',
        title: 'SERIAL<br>KILLER',
        titleStyle: 'color: var(--c-white); text-shadow: 3px 3px 0 #3d0000, -1px -1px 0 var(--c-red);',
        subtitle: 'PEMBUNUH BAYARAN',
        subtitleStyle: 'background: #0a0000; color: var(--c-red);',
        quote: '"BUKAN SERIGALA. BUKAN WARGA. AKU JAUH LEBIH BERBAHAYA."',
        quoteStyle: 'color: var(--c-red);',
        descHtml: `<strong>PEMBANTAIAN TUNGGAL:</strong> Setiap malam, bunuh 1 pemain. Sendirian. Targetmu bebas \u2014 siapapun. <strong>Kondisi menang:</strong> jadilah satu-satunya yang tersisa. Tidak ada pengecualian.`,
        code: 'SKL-KILL',
        codeStyle: 'background: #0a0000; color: var(--c-red); border-color: #8b0000;'
    },
    {
        id: 'IDT-FOOL',
        style: '--accent: var(--c-yellow); --title-color: var(--c-black); --rot-slash: 8deg; --slash-top: -12mm; --slash-bot: 43mm; --rot-header: 4deg; --rot-sub: -4deg; --rot-quote: -2deg; --rot-code: 3deg; --title-size: 20pt;',
        slashStyle: 'background: repeating-conic-gradient(var(--c-yellow) 0% 25%, var(--c-black) 0% 50%) 0 0 / 12px 12px;',
        faction: 'CHAOS',
        title: 'IDI<br>OT',
        titleStyle: 'color: var(--c-black); text-shadow: 2px 2px 0 #b8860b;',
        subtitle: 'SANG PANDIR',
        subtitleStyle: 'background: var(--c-black); color: var(--c-yellow);',
        quote: '"TUNGGU, KITA SEHARUSNYA MEMBUNUH ORANG? KUKIRA INI PESTA!"',
        quoteStyle: 'color: #b8860b;',
        descHtml: `<strong>KEBAL EKSEKUSI:</strong> Jika warga mem-voting mati dirimu di siang hari, kamu <strong>tidak mati</strong> \u2014 malah kehilangan hak voting selamanya. Tetapi kamu masih hidup dan lanjut bermain.`,
        code: 'IDT-FOOL',
        codeStyle: 'background: var(--c-black); color: var(--c-yellow); border-color: #b8860b;'
    },
    {
        id: 'PRC-CROWN',
        style: '--accent: var(--c-cyan); --title-color: var(--c-white); --rot-slash: 4deg; --slash-top: -8mm; --slash-bot: 40mm; --rot-header: 2deg; --rot-sub: -3deg; --rot-quote: -1deg; --rot-code: 2deg; --title-size: 20pt;',
        slashStyle: 'background: linear-gradient(112deg, #001a26 0%, #003d5c 45%, var(--c-cyan) 100%);',
        faction: 'SOVEREIGN',
        title: 'PRIN<br>CE',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #001a26, -1px -1px 0 var(--c-cyan);',
        subtitle: 'ANAK MAHKOTA',
        subtitleStyle: 'background: #001a26; color: var(--c-cyan);',
        quote: '"EKSEKUSI AKU? PIKIRKAN LAGI. KOTA INI MILIK KELUARGAKU."',
        quoteStyle: 'color: var(--c-cyan);',
        descHtml: `<strong>IMUNITAS MAHKOTA:</strong> Jika warga mem-voting mati dirimu, eksekusi <strong>dibatalkan otomatis</strong> sekali seumur game \u2014 identitasmu terbuka untuk semua. Setelah itu, kamu bisa dieksekusi normal.`,
        code: 'PRC-CROWN',
        codeStyle: 'background: #001a26; color: var(--c-cyan); border-color: var(--c-cyan);'
    },
    {
        id: 'LGR-SPY',
        style: '--accent: var(--c-magenta); --title-color: var(--c-white); --rot-slash: -5deg; --slash-top: -7mm; --slash-bot: 38mm; --rot-header: -2deg; --rot-sub: 3deg; --rot-quote: 1.5deg; --rot-code: -2deg; --title-size: 17pt;',
        slashStyle: 'background: linear-gradient(120deg, #2d0030 0%, #6a0075 50%, var(--c-magenta) 100%);',
        faction: 'ALLIANCE',
        title: 'LITTLE<br>GIRL',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 #2d0030, -1px -1px 0 #6a0075;',
        subtitle: 'SI MATA-MATA CILIK',
        subtitleStyle: 'background: #2d0030; color: var(--c-magenta);',
        quote: '"AKU TIDAK TIDUR. AKU MELIHAT SEMUANYA DARI CELAH MATAKU."',
        quoteStyle: 'color: var(--c-magenta);',
        descHtml: `<strong>MENGINTIP GELAP:</strong> Setiap malam, coba <strong>mengintip aksi kawanan</strong>. Jika ketahuan oleh serigala \u2014 kamu langsung dibunuh. Berani? Informasimu bisa menyelamatkan kota.`,
        code: 'LGR-SPY',
        codeStyle: 'background: #2d0030; color: var(--c-magenta); border-color: #6a0075;'
    },
    {
        id: 'card_back',
        style: '--accent: var(--c-red); --title-color: var(--c-white); --slash-top: -5mm; --slash-bot: 25mm; --rot-slash: -8deg; --rot-header: 3deg; --rot-sub: -2deg; --title-size: 20pt;',
        slashStyle: 'background: var(--c-black);',
        faction: 'CLASSIFIED',
        factionStyle: 'color: var(--c-white);',
        title: 'WHO<br>ARE<br>YOU?',
        titleStyle: 'color: var(--c-white); text-shadow: 2px 2px 0 var(--accent), -1px -1px 0 var(--accent);',
        subtitle: 'NIGHTMARE ASYLUM',
        subtitleStyle: 'background: var(--accent);',
        artStyle: 'margin-top: -10mm;',
        bottomStyle: 'padding-top: 1mm; background: none;',
        quote: '"JANGAN PERCAYA SIAPAPUN.<br>BAHKAN DIRIMU SENDIRI."',
        quoteStyle: 'text-align: center; font-size: 8.5pt;',
        descHtml: `<div class="back-desc-area">
                        <div class="barcode">|| | ||| | || |||</div>
                        <div style="font-family: 'Space Mono', monospace; font-size: 4pt; color: var(--c-black); font-weight: bold; margin-top: 1mm;">TOP SECRET // DO NOT OPEN</div>
                    </div>`,
        code: 'DECK-XX',
        codeStyle: 'background: var(--c-black); color: var(--c-white);'
    }
];
