const tornarchDeckData = [
    {
        id: "mdr-00-nn",
        isBack: false,
        faction: "NEUTRAL",
        code: "MDR-00-NN",
        titleEn: "MODERATOR",
        titleId: "Moderator",
        quote: '"Akulah suara alam semesta ini. Aturan berlaku bagi semua — serigala maupun warga."',
        desc: "PENGUASA MALAM:<br>Bukan pemain, melainkan <strong>pemandu jalannya permainan</strong>. Moderator memulai setiap fase, menjaga waktu, dan memastikan tidak ada yang melanggar aturan suci malam.",
        cssVars: "--c-accent: #7f8c8d; --c-dark: #2c3e50; --svg-rot: 0deg;"
    },
    {
        id: "wwf-06-sh",
        isBack: false,
        faction: "SHADOW",
        code: "WWF-06-SH",
        titleEn: "WEREWOLF",
        titleId: "Serigala",
        quote: '"Kami bersembunyi di balik senyum kalian di siang hari, dan mencabik leher kalian di malam hari."',
        desc: "MANGSA MALAM:<br>Bangun setiap malam bersama klan serigala lainnya. Berdiskusilah, lalu <strong>pilih 1 pemain untuk dibunuh</strong> dan dihabisi sebelum fajar menyingsing.",
        cssVars: "--c-accent: #b30000; --c-dark: #000000; --svg-rot: -3deg;"
    },
    {
        id: "ser-01-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "SER-01-AL",
        titleEn: "THE SEER",
        titleId: "Sang Peramal",
        quote: '"Kalian boleh menutup mata saat fajar, tapi rasi bintang tak pernah berbohong di kegelapan."',
        desc: "MATA BATIN:<br>Setiap malam, kau dapat <strong>menerawang 1 pemain</strong> untuk mengetahui identitas sejatinya. Cari tahu siapa serigala yang bersembunyi.",
        cssVars: "--c-accent: #c89b3c; --c-dark: #0f2c59; --svg-rot: 0deg;"
    },
    {
        id: "hnt-99-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "HNT-99-AL",
        titleEn: "THE HUNTER",
        titleId: "Sang Pemburu",
        quote: '"Aku mungkin akan mati malam ini. Tapi aku takkan sudi turun ke neraka sendirian."',
        desc: "PELATUK TERAKHIR:<br>Saat kau terbunuh oleh serigala atau dieksekusi warga, kau memiliki 1 detik terakhir untuk <strong>menembak mati 1 pemain</strong> pilihanmu seketika.",
        cssVars: "--c-accent: #d35400; --c-dark: #2e1f18; --svg-rot: 0deg;"
    },
    {
        id: "jst-00-ch",
        isBack: false,
        faction: "CHAOS",
        code: "JST-00-CH",
        titleEn: "THE JESTER",
        titleId: "Sang Badut",
        quote: '"Ayo, gantung aku! Sorakan kalian adalah simfoni terindah untuk merayakan kemenanganku!"',
        desc: "TARGET MATI:<br>Tujuanmu adalah memanipulasi warga agar curiga dan mengeksekusimu di tiang gantungan. Jika kau digantung, kau <strong>MENANG MUTLAK</strong> sendirian.",
        cssVars: "--c-accent: #8e44ad; --c-dark: #2c0e3b; --svg-rot: 2deg;"
    },
    {
        id: "grd-77-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "GRD-77-AL",
        titleEn: "THE GUARDIAN",
        titleId: "Sang Pelindung",
        quote: '"Sembunyilah di balik punggungku. Malam ini, tak ada satu pun taring yang akan menembus kulitmu."',
        desc: "AEGIS SUCI:<br>Setiap malam, <strong>pilih 1 pemain</strong> untuk dilindungi. Jika pemain tersebut diserang oleh serigala, ia akan selamat dari kematian.",
        cssVars: "--c-accent: #2980b9; --c-dark: #1a252f; --svg-rot: 0deg;"
    },
    {
        id: "alw-02-sh",
        isBack: false,
        faction: "SHADOW",
        code: "ALW-02-SH",
        titleEn: "ALPHA WOLF",
        titleId: "Serigala Alfa",
        quote: '"Aku bukan sekadar serigala. Aku badai yang datang sebelum kehancuran total."',
        desc: "PEMIMPIN KLAN:<br>Setiap malam, pimpin kawanan memilih korban. Sebagai Alfa, kamu dapat <strong>merekrut 1 warga biasa</strong> menjadi serigala baru jika ada anggota klan yang terbunuh.",
        cssVars: "--c-accent: #8b0000; --c-dark: #1a0000; --svg-rot: -5deg;"
    },
    {
        id: "cpd-03-ch",
        isBack: false,
        faction: "CHAOS",
        code: "CPD-03-CH",
        titleEn: "CUPID",
        titleId: "Sang Panah Asmara",
        quote: '"Aku tembakkan cinta, tapi cinta di sini bisa membunuhmu berdua sekaligus."',
        desc: "TALI MERAH:<br>Di malam pertama, <strong>tunjuk 2 pemain sebagai sepasang kekasih</strong>. Jika salah satunya mati, yang lain ikut mati karena patah hati. Mereka mengejar tujuan sendiri sebagai pasangan.",
        cssVars: "--c-accent: #e91e63; --c-dark: #3a0020; --svg-rot: 3deg;"
    },
    {
        id: "wtc-04-sh",
        isBack: false,
        faction: "SHADOW",
        code: "WTC-04-SH",
        titleEn: "THE WITCH",
        titleId: "Sang Penyihir",
        quote: '"Dua ramuan di tanganku: satu menyelamatkan, satu melenyapkan. Hanya satu kesempatan masing-masing."',
        desc: "DUA AMPUL:<br>Kau memiliki <strong>ramuan kehidupan</strong> (selamatkan 1 korban serigala) dan <strong>ramuan racun</strong> (bunuh 1 pemain pilihan). Masing-masing hanya bisa dipakai 1 kali.",
        cssVars: "--c-accent: #1abc9c; --c-dark: #0e0033; --svg-rot: -2deg;"
    },
    {
        id: "wzd-05-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "WZD-05-AL",
        titleEn: "THE WIZARD",
        titleId: "Sang Penyihir Putih",
        quote: '"Mantraku bukan untuk menyerang, tapi untuk membaca. Pikiran kalian terbuka di hadapanku seperti buku."',
        desc: "MANTRA WAHYU:<br>Setiap dua malam sekali, kau dapat <strong>melihat hasil aksi seluruh peran khusus</strong> yang terjadi tadi malam tanpa diketahui siapapun.",
        cssVars: "--c-accent: #9b59b6; --c-dark: #1c0a3a; --svg-rot: 0deg;"
    },
    {
        id: "vet-06-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "VET-06-AL",
        titleEn: "VETERAN",
        titleId: "Sang Veteran",
        quote: '"Aku sudah melihat terlalu banyak kematian. Malam ini aku siap menembak siapapun yang mendekat."',
        desc: "WASPADA TOTAL:<br>Kau memiliki <strong>3 malam siaga</strong>. Saat siaga aktif, siapapun yang menemuimu malam itu — termasuk peran baik — akan langsung terbunuh. Gunakan dengan bijak.",
        cssVars: "--c-accent: #8d6e35; --c-dark: #1e1408; --svg-rot: 0deg;"
    },
    {
        id: "bdg-07-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "BDG-07-AL",
        titleEn: "BODYGUARD",
        titleId: "Sang Bodyguard",
        quote: '"Kau boleh menyerangnya, tapi kau harus melalui aku terlebih dahulu."',
        desc: "TAMENG NYAWA:<br>Setiap malam, <strong>lindungi 1 pemain</strong>. Jika pemain itu diserang, kamu yang mati menggantikannya. Kamu tidak bisa melindungi dirimu sendiri.",
        cssVars: "--c-accent: #546e7a; --c-dark: #0d1b2a; --svg-rot: 0deg;"
    },
    {
        id: "prs-08-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "PRS-08-AL",
        titleEn: "PRIEST",
        titleId: "Sang Pastor",
        quote: '"Tuhan melihat segalanya. Di bawah cahaya-Nya, kebohongan serigala tak bisa tersembunyi."',
        desc: "BERKAH SUCI:<br>Sekali dalam permainan, kau dapat <strong>memberkati 1 pemain</strong>. Pemain itu kebal dari serangan serigala 1 malam dan identitasnya tersembunyi dari ramalan Peramal.",
        cssVars: "--c-accent: #f39c12; --c-dark: #1a130a; --svg-rot: 0deg;"
    },
    {
        id: "myr-09-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "MYR-09-AL",
        titleEn: "MAYOR",
        titleId: "Sang Walikota",
        quote: '"Suara rakyat adalah hukum tertinggi. Dan aku memiliki dua suara."',
        desc: "HAK VETO GANDA:<br>Saat identitasmu terungkap, <strong>suaramu dihitung dua kali</strong> dalam setiap pemungutan suara eksekusi. Warga mendapat harapan, tapi kau menjadi target utama serigala.",
        cssVars: "--c-accent: #c0392b; --c-dark: #2c0000; --svg-rot: 0deg;"
    },
    {
        id: "shr-10-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "SHR-10-AL",
        titleEn: "SHERIFF",
        titleId: "Sang Sherif",
        quote: '"Lencana ini bukan sekadar besi. Ini adalah janji untuk melindungi setiap jiwa di kota ini."',
        desc: "OTORITAS HUKUM:<br>Setiap malam, kau dapat <strong>menyelidiki 1 pemain</strong>. Kau tahu apakah mereka berpaksi gelap atau terang. Hasil penyelidikanmu lebih akurat dari Peramal.",
        cssVars: "--c-accent: #f1c40f; --c-dark: #1a1a0a; --svg-rot: 0deg;"
    },
    {
        id: "vl1-11-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "VL1-11-AL",
        titleEn: "VILLAGER",
        titleId: "Warga Kota",
        quote: '"Kami mungkin tidak punya kekuatan sihir. Tapi bersama, kami adalah mayoritas."',
        desc: "SUARA RAKYAT:<br>Kau tidak memiliki kemampuan khusus. <strong>Kekuatanmu ada di akal dan diskusi</strong>. Identifikasi serigala lewat logika, observasi, dan kerjasama warga di siang hari.",
        cssVars: "--c-accent: #27ae60; --c-dark: #0d2918; --svg-rot: 1deg;"
    },
    {
        id: "vl2-12-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "VL2-12-AL",
        titleEn: "VILLAGER",
        titleId: "Warga Kota",
        quote: '"Serigala bersembunyi di antara kita. Satu-satunya senjata kita adalah kebenaran."',
        desc: "SUARA RAKYAT:<br>Kau tidak memiliki kemampuan khusus. <strong>Kekuatanmu ada di akal dan diskusi</strong>. Pelajari pola bicara, reaksi, dan alibi setiap pemain untuk menemukan sang serigala.",
        cssVars: "--c-accent: #16a085; --c-dark: #0a1e1c; --svg-rot: -1deg;"
    },
    {
        id: "vl3-13-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "VL3-13-AL",
        titleEn: "VILLAGER",
        titleId: "Warga Kota",
        quote: '"Malam selalu berakhir. Dan saat fajar tiba, kebenaran akan selalu menang."',
        desc: "SUARA RAKYAT:<br>Kau tidak memiliki kemampuan khusus. <strong>Kekuatanmu ada di akal dan diskusi</strong>. Ingat setiap gerakan mencurigakan dan gunakan saat debat siang hari dimulai.",
        cssVars: "--c-accent: #e67e22; --c-dark: #1f0e00; --svg-rot: 2deg;"
    },
    {
        id: "ww2-14-sh",
        isBack: false,
        faction: "SHADOW",
        code: "WW2-14-SH",
        titleEn: "WEREWOLF",
        titleId: "Serigala",
        quote: '"Mereka mengira wajah ramahku adalah bukti kepolosanku. Keliru besar."',
        desc: "MANGSA MALAM:<br>Bangun setiap malam bersama klan serigala lainnya. Berdiskusilah, lalu <strong>pilih 1 pemain untuk dibunuh</strong> dan dihabisi sebelum fajar menyingsing.",
        cssVars: "--c-accent: #e74c3c; --c-dark: #180000; --svg-rot: 3deg;"
    },
    {
        id: "lnw-15-sh",
        isBack: false,
        faction: "ALLIANCE",
        code: "LNW-15-SH",
        titleEn: "LONE WOLF",
        titleId: "Serigala Liar",
        quote: '"Aku dikira warga biasa. Tapi saat mereka menemukanku... aku bukan lagi yang dulu."',
        desc: "TRANSFORMASI:<br>Kau mulai sebagai <strong>warga biasa</strong>. Jika serigala menemukanmu di malam hari, kau <strong>langsung berubah menjadi serigala</strong> dan bergabung dengan kawanan untuk sisa permainan.",
        cssVars: "--c-accent: #6c5ce7; --c-dark: #0d0820; --svg-rot: -3deg;"
    },
    {
        id: "dpg-16-ch",
        isBack: false,
        faction: "CHAOS",
        code: "DPG-16-CH",
        titleEn: "DOPPELGANGER",
        titleId: "Sang Penduplikasi",
        quote: '"Aku bisa menjadi siapa saja. Bahkan dirimu sendiri."',
        desc: "BAYANGAN HIDUP:<br>Di malam pertama, <strong>pilih 1 pemain sebagai target</strong>. Saat target mati, kamu mengambil alih peran dan kemampuannya secara penuh seolah kamu adalah mereka.",
        cssVars: "--c-accent: #00bcd4; --c-dark: #002a30; --svg-rot: 0deg;"
    },
    {
        id: "skl-17-ch",
        isBack: false,
        faction: "CHAOS",
        code: "SKL-17-CH",
        titleEn: "SERIAL KILLER",
        titleId: "Pembunuh Berantai",
        quote: '"Serigala membunuh karena lapar. Aku membunuh karena aku bisa."',
        desc: "PISAU SENYAP:<br>Setiap malam, kau <strong>membunuh 1 pemain pilihanmu sendiri</strong>, terlepas dari aksi serigala. Kamu menang jika satu-satunya yang tersisa. Tidak ada yang aman darimu.",
        cssVars: "--c-accent: #e53935; --c-dark: #0a0000; --svg-rot: -4deg;"
    },
    {
        id: "idt-18-ch",
        isBack: false,
        faction: "CHAOS",
        code: "IDT-18-CH",
        titleEn: "IDIOT",
        titleId: "Sang Orang Bodoh",
        quote: '"Mereka mau menggantungku? Bagus sekali! Aku bahkan tidak tahu ini permainan!"',
        desc: "KEBAL HUKUM:<br>Jika warga memilih mengeksekusimu, <strong>kamu selamat dan tetap hidup</strong> (tapi kehilangan hak suara selamanya). Jika dibunuh serigala, kamu mati normal. Kebodohan adalah senjatamu.",
        cssVars: "--c-accent: #ff9800; --c-dark: #1a0d00; --svg-rot: 4deg;"
    },
    {
        id: "prc-19-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "PRC-19-AL",
        titleEn: "PRINCE",
        titleId: "Sang Pangeran",
        quote: '"Rakyat boleh memilihku untuk digantung, tapi tahta ini melindungiku sekali saja."',
        desc: "KEKEBALAN KERAJAAN:<br>Jika warga memilih mengeksekusimu, <strong>kamu terungkap sebagai Pangeran dan dibebaskan</strong>. Kemampuan ini hanya berlaku satu kali. Setelah itu, kamu bisa mati normal.",
        cssVars: "--c-accent: #5c6bc0; --c-dark: #0d0e2b; --svg-rot: 0deg;"
    },
    {
        id: "lgl-20-al",
        isBack: false,
        faction: "ALLIANCE",
        code: "LGL-20-AL",
        titleEn: "LITTLE GIRL",
        titleId: "Si Gadis Kecil",
        quote: '"Aku pura-pura tidur, tapi mataku selalu terbuka sedikit saat serigala bergerak."',
        desc: "MATA MENGINTIP:<br>Saat serigala membuka mata di malam hari, kamu boleh <strong>mengintip sebentar</strong> untuk melihat siapa mereka. Tapi jika serigala menyadarimu, kamu langsung dibunuh.",
        cssVars: "--c-accent: #f06292; --c-dark: #2a0a1c; --svg-rot: 1deg;"
    },
    {
        id: "card-back",
        isBack: true,
        faction: "WEREWOLF",
        code: "",
        titleEn: "",
        titleId: "Premium Deck",
        desc: "<b>EST. 2026</b> — ASYMMETRIC EDITION",
        cssVars: "--c-accent: #d4af37; --c-dark: #1a1a1a; --svg-rot: 0deg;"
    }
];
