const asylumDeckData = [
    {
        id: "SP·01",
        code: "DOC: SUP-00",
        faction: "SUPREME",
        colorVar: "var(--fac-sup)",
        accentKey: "moderator",
        titleId: "SANG NARATOR",
        titleEn: "MODERATOR",
        subtitle: "The Architect",
        quote: "\"Kalian hanyalah bidak rapuh yang menari di atas genangan darah hingga aku menutup panggung cerita ini.\"",
        ability: "Menjadi pemandu yang mengontrol seluruh interaksi pemain di setiap fase."
    },
    {
        id: "VL·01",
        code: "DOC: ALL-01",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "seer",
        titleId: "PERAMAL",
        titleEn: "SEER",
        subtitle: "The Third Eye",
        quote: "\"Meskipun kau berbalut sutra sempurna, mata ini tak tertipu melihat roh serigala jahat di bayanganmu.\"",
        ability: "Setiap malam memeriksa identitas 1 pemain. Moderator memberi isyarat apabila target adalah seekor Serigala."
    },
    {
        id: "WW·03",
        code: "DOC: ALPH-00",
        faction: "SHADOW",
        colorVar: "var(--fac-shd)",
        accentKey: "alphawolf",
        titleId: "ALPHA SERIGALA",
        titleEn: "ALPHA WOLF",
        subtitle: "The Blood Commander",
        quote: "\"Gigitanku takkan sekedar membunuhmu, melainkan membangkitkanmu sebagai jenderal baru dalam koloni bayangan tergelap kami.\"",
        ability: "Dapat mencegah target mati pada malam itu namun mengubahnya mutlak menjadi Serigala. (1x seumur hidup)"
    },
    {
        id: "NT·01",
        code: "DOC: CHS-01",
        faction: "CHAOS",
        colorVar: "var(--fac-chs)",
        accentKey: "jester",
        titleId: "BADUT",
        titleEn: "JESTER",
        subtitle: "The Trickster",
        quote: "\"Silakan seret tubuh gilaku menuju tiang gantungan. Di ujung tali itulah letak kejayaan mutlak kemenanganku.\"",
        ability: "Akan langsung memenangkan permainan jika ia mati divonis gantung oleh voting warga."
    },
    {
        id: "NT·03",
        code: "DOC: CHS-03",
        faction: "CHAOS",
        colorVar: "var(--fac-chs)",
        accentKey: "cupid",
        titleId: "CUPID",
        titleEn: "CUPID",
        subtitle: "The Cursed Archer",
        quote: "\"Bukan takdir agung merajut benang nyawa ini. Panah beracunku memaksamu berpasangan dan mati bersama-sama.\"",
        ability: "Di malam pertama, menunjuk dua pemain. Jika salah satu dari mereka tewas, yang lainnya otomatis ikut tewas."
    },
    {
        id: "VL·04",
        code: "DOC: ALL-04",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "hunter",
        titleId: "PEMBURU",
        titleEn: "HUNTER",
        subtitle: "The Last Shot",
        quote: "\"Rencanakanlah skenario mautku esok lusa... Namun takkan kubiarkan senapan perakku mengantarkanku turun ke neraka sendirian.\"",
        ability: "Apabila ia mati (dimangsa atau digantung), ia berhak seketika menembak mati 1 pemain manapun."
    },
    {
        id: "VL·02",
        code: "DOC: ALL-02",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "guardian",
        titleId: "PENJAGA",
        titleEn: "GUARDIAN",
        subtitle: "The Iron Shield",
        quote: "\"Tak ada satupun darah segar yang mewarnai gelapnya malam. Tameng suciku takkan sanggup dipenggal cakar kalian.\"",
        ability: "Pilih 1 pemain setiap malam. Orang tersebut sepenuhnya kebal dari upaya pembunuhan komplotan Serigala."
    },
    {
        id: "VL·03",
        code: "DOC: ALL-03",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "witch",
        titleId: "PENYIHIR",
        titleEn: "WITCH",
        subtitle: "The Pale Alchemist",
        quote: "\"Teruslah kalian berebut napas menatap maut. Kelangsungan takdir siapa yang layu murni tanggungan hiburanku semata.\"",
        ability: "Memiliki 1 ramuan pelindung untuk menggagalkan pembunuhan Serigala, dan 1 racun untuk mematikan siapa saja secara instan."
    },
    {
        id: "WW·01",
        code: "DOC: MUT-01",
        faction: "SHADOW",
        colorVar: "var(--fac-shd)",
        accentKey: "werewolf",
        titleId: "SERIGALA",
        titleEn: "WEREWOLF",
        subtitle: "The Night Predator",
        quote: "\"Cahaya buas rembulan tak menuntut perdamaian tawar. Bila purnama meradang di dada, lehermu murni harus terburai maut.\"",
        ability: "Bangun setiap malam, berdiskusi dengan semua serigala lain, lalu sepakat menunjuk 1 orang untuk dibunuh."
    },
    {
        id: "VL·13",
        code: "DOC: ALL-13",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "wizard",
        titleId: "PENYIHIR PENUKAR",
        titleEn: "WIZARD",
        subtitle: "The Fate Swapper",
        quote: "\"Terlelaplah selagi raga masih berpadu napas. Sekali jentik magis telunjukku ini, nasib keutuhanmu mendadak tertukar malapetaka.\"",
        ability: "HANYA MALAM PERTAMA: Memilih dua pemain. Peran mereka berdua ditukar secara rahasia dan permanen seumur hidup."
    },
    {
        id: "VL·20",
        code: "DOC: ALL-20",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "veteran",
        titleId: "VETERAN TUA",
        titleEn: "VETERAN",
        subtitle: "The Scarred Survivor",
        quote: "\"Garis lebam di dahiku tiada bermakna takluk menyerah... tapi jejak abadi ratusan luka yang tumpul mengiris tempurung maut.\"",
        ability: "Apabila diserang Serigala di malam hari, ia kebal sementara waktu dan baru akan mati pada siang harinya."
    },
    {
        id: "VL·18",
        code: "DOC: ALL-18",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "bodyguard",
        titleId: "PRAJURIT",
        titleEn: "BODYGUARD",
        subtitle: "The Living Bastion",
        quote: "\"Meski hantaman memecah lebur benteng terakhirku... Selama kakiku tegak kokoh melangkah, takkan kuserahkan incaran ke punggung kelam.\"",
        ability: "Menunjuk target untuk dijaga nyawanya semalaman murni. Bila diserang malam itu, Prajurit ini yang lurus mengorbankan nyawa."
    },
    {
        id: "VL·19",
        code: "DOC: ALL-19",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "priest",
        titleId: "PENDETA",
        titleEn: "PRIEST",
        subtitle: "The Fallen Saint",
        quote: "\"Dosa pekat menelan ratapan tak bersalah terkurung derita tangisan malam kelabu pasrah merengkuh ajal maut.\"",
        ability: "Satu tuangan Suci. Jika disiram ke serigala, target langsung tewas. Namun bila meleset mengenai manusia biasa, ia mati."
    },
    {
        id: "VL·10",
        code: "DOC: ALL-10",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "mayor",
        titleId: "KEPALA DESA",
        titleEn: "MAYOR",
        subtitle: "The Iron Gavel",
        quote: "\"Berhentilah menggonggong bodoh melontarkan omong kosong sidang gantung rapuh yang seketika luntur memutih ditentang otoritas palu jempol angkuhku murni sejati.\"",
        ability: "Privilese utuh absolut sekali beraksi mutlak membebaskan dan membatalkan tuntas seluruh suara ancaman gantung massa warga pengadilan siang murni fana."
    },
    {
        id: "VL·09",
        code: "DOC: ALL-09",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "sheriff",
        titleId: "POLISI",
        titleEn: "SHERIFF",
        subtitle: "The Double Verdict",
        quote: "\"Pengakuan dusta bersimpuh memelas ampun tak berharga satu gram di mimpiku. Suara laras besiku menjadi satu-satunya eksekutor validasi purna timbangan mutlak abadi.\"",
        ability: "Setiap hak suara pilihannya dalam sidang voting gantung mendadak sangat bernilai ganda (Terhitung memotong tuntas bobot 2 suara)."
    },
    {
        id: "VL·14",
        code: "DOC: PTR-14",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "villager",
        titleId: "WARGA DESA",
        titleEn: "VILLAGER",
        subtitle: "The Innocent",
        quote: "\"Jangan meremehkan ikatan darah kamilah yang akan memancung lilitan monster ini.\"",
        ability: "Tidak memiliki kemampuan malam. Hanya berhak ikut voting siang untuk menggantung tersangka."
    },
    {
        id: "VL·15",
        code: "DOC: PTR-15",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "villager",
        titleId: "WARGA DESA",
        titleEn: "VILLAGER",
        subtitle: "The Innocent",
        quote: "\"Duka derita tangis warga kami akan menggerus tipuan kebohongan maut serigala.\"",
        ability: "Tidak memiliki kemampuan malam. Hanya berhak ikut voting siang untuk menggantung tersangka."
    },
    {
        id: "VL·16",
        code: "DOC: PTR-16",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "villager",
        titleId: "WARGA DESA",
        titleEn: "VILLAGER",
        subtitle: "The Innocent",
        quote: "\"Kepanikan massal menyebar, namun algojo tali gantungan kami siap menjerat kalian.\"",
        ability: "Tidak memiliki kemampuan malam. Hanya berhak ikut voting siang untuk menggantung tersangka."
    },
    {
        id: "WW·02",
        code: "DOC: MUT-02",
        faction: "SHADOW",
        colorVar: "var(--fac-shd)",
        accentKey: "werewolf",
        titleId: "SERIGALA",
        titleEn: "WEREWOLF",
        subtitle: "The Night Predator",
        quote: "\"Raungan nada ini adalah irama ritmik menjemput ujung usiamu hingga kaku.\"",
        ability: "Bangun setiap malam bersama sisa klan Serigala. Diskusi untuk sepakat membunuh 1 korban."
    },
    {
        id: "WW·05",
        code: "DOC: LONE-05",
        faction: "SHADOW",
        colorVar: "var(--fac-shd)",
        accentKey: "lonewolf",
        titleId: "SERIGALA TUNGGAL",
        titleEn: "LONE WOLF",
        subtitle: "The Outcast",
        quote: "\"Sumpah ikatan serigala hanyalah tontonan. Kejayaan nyata adalah jika aku satu-satunya pemenangnya.\"",
        ability: "Membunuh bersama serigala lain, TAPI hanya berhak menang jika ia berhasil menjadi pemenang terakhir."
    },
    {
        id: "NT·04",
        code: "DOC: CHS-04",
        faction: "CHAOS",
        colorVar: "var(--fac-chs)",
        accentKey: "doppelganger",
        titleId: "PENIRU",
        titleEn: "DOPPELGANGER",
        subtitle: "The Mirror Soul",
        quote: "\"Lekuk ketakutanmu kucuri utuh, mencabut wajah aslimu dan menggantikannya sempurnah purna tak bersisa.\"",
        ability: "HARI-1: Menunjuk bebas 1 pemain rahasia. Tatkala target tewas, si Peniru otomatis berubah merampas kemampuannya."
    },
    {
        id: "NT·05",
        code: "DOC: CHS-05",
        faction: "CHAOS",
        colorVar: "var(--fac-chs)",
        accentKey: "serialkiller",
        titleId: "PEMBUNUH BERANTAI",
        titleEn: "SERIAL KILLER",
        subtitle: "The Indiscriminate",
        quote: "\"Mata kelam bajaku menyayat rata; entah kalian serigala tebal atau manusia miskin lemah tak berkutik.\"",
        ability: "Menang independen. Tiap malam tak memihak pihak manapun mencabut nyawa orang acak hingga tersisa dirinya saja."
    },
    {
        id: "VL·26",
        code: "DOC: ALL-26",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "idiot",
        titleId: "ORANG DUNGU",
        titleEn: "IDIOT",
        subtitle: "The Fool's Pardon",
        quote: "\"Kalian mencemooh wajah bodoh ini, padahal kalian yang bertingkat sinting membalas dendam mencekik saudara.\"",
        ability: "Diampuni palu hukuman sidang warga. Jika mayoritas menggantungnya mematikan, ia tidak tewas namun kehilangan hak vonis selamanya."
    },
    {
        id: "VL·35",
        code: "DOC: ALL-35",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "prince",
        titleId: "PANGERAN",
        titleEn: "PRINCE",
        subtitle: "The Untouchable",
        quote: "\"Tali kotor rakyat menjijikan ini tak pernah pantas menggantung leher urat napas angkuh bangsawan keturunanku.\"",
        ability: "Imunitas diplomatik mutlak. Jika diseret menuju eksekusi palu pengadilan mematikan siang hari oleh massa, ia seketika membatalkan kematiannya."
    },
    {
        id: "VL·07",
        code: "DOC: ALL-07",
        faction: "ALLIANCE",
        colorVar: "var(--fac-all)",
        accentKey: "littlegirl",
        titleId: "GADIS KECIL",
        titleEn: "LITTLE GIRL",
        subtitle: "The Silent Witness",
        quote: "\"Mata polos lelah ini mengintip dari celah belantara semu, menatap basah tetesan luka kawan dicabik biadab.\"",
        ability: "Satu-satunya yang rahasia boleh mengintip kelompok pembunuh malam hari bangun. Sangat beresiko seketika tewas lurus bila aksinya disadari serigala."
    }
];
